# Generated by Django 5.2.5 on 2025-08-30 14:15

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admissionapplication_archivedemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('admission_start_date', models.DateField(blank=True, null=True)),
                ('admission_end_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExtendedAdmissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('preferred_start_date', models.DateField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='draft', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('other', 'Other')], max_length=50)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_occupation', models.CharField(blank=True, max_length=200)),
                ('guardian_employer', models.CharField(blank=True, max_length=200)),
                ('secondary_guardian_name', models.CharField(blank=True, max_length=200)),
                ('secondary_guardian_relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('other', 'Other')], max_length=50)),
                ('secondary_guardian_phone', models.CharField(blank=True, max_length=20)),
                ('secondary_guardian_email', models.EmailField(blank=True, max_length=254)),
                ('previous_school_name', models.CharField(max_length=300)),
                ('previous_school_address', models.TextField(blank=True)),
                ('last_class_attended', models.CharField(max_length=100)),
                ('last_attendance_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)])),
                ('reason_for_leaving', models.TextField(blank=True)),
                ('academic_performance', models.CharField(blank=True, choices=[('excellent', 'Excellent (90-100%)'), ('very_good', 'Very Good (80-89%)'), ('good', 'Good (70-79%)'), ('satisfactory', 'Satisfactory (60-69%)'), ('needs_improvement', 'Needs Improvement (<60%)')], max_length=50)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('height', models.IntegerField(blank=True, help_text='Height in centimeters', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('weight', models.IntegerField(blank=True, help_text='Weight in kilograms', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)])),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions, allergies, or special needs')),
                ('medications', models.TextField(blank=True, help_text='Current medications and dosages')),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relationship', models.CharField(max_length=100)),
                ('terms_agreement', models.BooleanField(default=False)),
                ('fee_acknowledgment', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.academicyear')),
                ('course_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('immunization_record', 'Under 5 Card (Immunization Record)'), ('birth_certificate', 'Birth Certificate'), ('utility_bill', 'Utility Bill (Proof of Residence)'), ('parent1_id', 'National Registration Card - Parent 1'), ('parent2_id', 'National Registration Card - Parent 2'), ('student_photo', 'Student Passport Photo'), ('academic_transcript', 'Academic Transcript'), ('other', 'Other Document')], max_length=50)),
                ('file', models.FileField(upload_to=core.models.upload_to_documents, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.extendedadmissionapplication')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionApplicationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.extendedadmissionapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplicationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_notes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.extendedadmissionapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['tenant', 'is_active'], name='core_academ_tenant__7a3f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='extendedadmissionapplication',
            index=models.Index(fields=['tenant', 'status'], name='core_extend_tenant__adc8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='extendedadmissionapplication',
            index=models.Index(fields=['application_number'], name='core_extend_applica_65d134_idx'),
        ),
        migrations.AddIndex(
            model_name='extendedadmissionapplication',
            index=models.Index(fields=['academic_year', 'status'], name='core_extend_academi_8c2a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='extendedadmissionapplication',
            index=models.Index(fields=['course_applied', 'status'], name='core_extend_course__74c565_idx'),
        ),
        migrations.AddIndex(
            model_name='admissiondocument',
            index=models.Index(fields=['tenant', 'application'], name='core_admiss_tenant__fee0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='admissiondocument',
            index=models.Index(fields=['document_type'], name='core_admiss_documen_aa7ab7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='admissiondocument',
            unique_together={('application', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='admissionapplicationstatus',
            index=models.Index(fields=['tenant', 'application'], name='core_admiss_tenant__d28837_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplicationnote',
            index=models.Index(fields=['tenant', 'application'], name='core_admiss_tenant__3df569_idx'),
        ),
    ]
