# Generated by Django 5.2.5 on 2025-09-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_phone_number_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='academic_performance',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='fee_acknowledgment',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='guardian_employer',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='guardian_occupation',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='guardian_relationship',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='height',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='last_attendance_year',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='last_class_attended',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='reason_for_leaving',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='secondary_guardian_email',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='secondary_guardian_name',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='secondary_guardian_phone',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='secondary_guardian_relationship',
        ),
        migrations.RemoveField(
            model_name='extendedadmissionapplication',
            name='weight',
        ),
        migrations.AlterField(
            model_name='extendedadmissionapplication',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extendedadmissionapplication',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='extendedadmissionapplication',
            name='preferred_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedadmissionapplication',
            name='previous_school_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
