# Generated by Django 5.2.5 on 2025-09-01 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_extendedadmissionapplication_academic_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Terms and Conditions for Admission', max_length=255)),
                ('terms_content', models.TextField(help_text='HTML content for admission terms and conditions')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order in which terms appear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Admission Terms and Conditions',
                'verbose_name_plural': 'Admission Terms and Conditions',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'order'], name='core_admiss_tenant__954a5a_idx')],
            },
        ),
    ]
