# Generated by Django 5.2.5 on 2025-09-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_admission_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionterms',
            name='admission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admission fee amount (leave blank to use default)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admissionterms',
            name='fee_currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, GBP, ZMW)', max_length=3),
        ),
    ]
