# Generated by Django 5.2.5 on 2025-09-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_dynamic_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='fee_acknowledgment',
            field=models.BooleanField(default=False, help_text='Acknowledgment of admission fee payment requirement'),
        ),
    ]
