# Generated by Claude Code on 2025-09-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_fee_acknowledgment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='academic_year',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.academicyear'),
        ),
    ]