# Generated by Django 5.2.5 on 2025-09-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_batch_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionterms',
            name='fee_currency',
            field=models.CharField(default='ZMW', help_text='Currency code (e.g., USD, GBP, ZMW)', max_length=3),
        ),
        migrations.AlterField(
            model_name='batch',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.academicyear'),
        ),
        migrations.AlterField(
            model_name='extendedadmissionapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('step1_completed', 'Step 1 Completed'), ('step2_completed', 'Step 2 Completed'), ('step3_completed', 'Step 3 Completed'), ('step4_completed', 'Step 4 Completed'), ('step5_completed', 'Step 5 Completed'), ('step6_completed', 'Step 6 Completed'), ('step7_completed', 'Step 7 Completed'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('admitted', 'Admitted')], default='draft', max_length=50),
        ),
    ]
