# Generated by Django 5.2.5 on 2025-09-09 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_admissionterms_fee_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(help_text='QuickBooks App Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='QuickBooks App Client Secret', max_length=255)),
                ('redirect_uri', models.URLField(help_text='OAuth redirect URI')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', help_text='QuickBooks environment', max_length=20)),
                ('access_token', models.TextField(blank=True, help_text='Current access token', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token', null=True)),
                ('realm_id', models.CharField(blank=True, help_text='Company ID (realm_id)', max_length=255, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration time', null=True)),
                ('is_connected', models.BooleanField(default=False, help_text='Whether QuickBooks is currently connected')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last successful sync time', null=True)),
                ('sync_enabled', models.BooleanField(default=True, help_text='Whether automatic sync is enabled')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_country', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'QuickBooks Integration',
                'verbose_name_plural': 'QuickBooks Integrations',
                'indexes': [models.Index(fields=['tenant', 'is_connected'], name='core_quickb_tenant__6df16f_idx')],
            },
        ),
    ]
