# Generated by Django 5.2.5 on 2025-09-10 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_quickbooksintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_code', models.CharField(help_text='ISO currency code (e.g., USD, EUR, KES)', max_length=3)),
                ('currency_symbol', models.CharField(help_text='Currency symbol (e.g., $, €, KSh)', max_length=10)),
                ('currency_name', models.CharField(help_text='Full currency name (e.g., US Dollar, Euro, Kenyan Shilling)', max_length=100)),
                ('symbol_position', models.CharField(choices=[('before', 'Before amount ($100)'), ('after', 'After amount (100$)'), ('before_space', 'Before with space ($ 100)'), ('after_space', 'After with space (100 $)')], default='before', help_text='Position of currency symbol relative to amount', max_length=15)),
                ('decimal_places', models.PositiveIntegerField(default=2, help_text='Number of decimal places to display')),
                ('thousands_separator', models.CharField(choices=[(',', 'Comma (1,000)'), ('.', 'Period (1.000)'), (' ', 'Space (1 000)')], default=',', help_text='Separator for thousands', max_length=1)),
                ('decimal_separator', models.CharField(choices=[('.', 'Period (100.50)'), (',', 'Comma (100,50)')], default='.', help_text='Decimal separator', max_length=1)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is currently active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Currency Configuration',
                'verbose_name_plural': 'Currency Configurations',
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='core_curren_tenant__088386_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'is_active'), name='unique_active_currency_per_tenant')],
            },
        ),
    ]
