# Generated by Django 5.2.5 on 2025-09-10 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_currency_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('batch', 'Batch Discount'), ('individual', 'Individual Discount')], max_length=20)),
                ('discount_mode', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeParticular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creation_type', models.CharField(choices=[('all', 'All Students'), ('admission_no', 'By Admission Number'), ('student_category', 'By Student Category')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reconciliation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('payment', 'Fee Payment'), ('discount', 'Discount Applied'), ('fine', 'Fine Applied'), ('refund', 'Fee Refund'), ('adjustment', 'Fee Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FineSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fine_name', models.CharField(max_length=255)),
                ('days_after_due', models.IntegerField()),
                ('fine_mode', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='percentage', max_length=20)),
                ('fine_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['days_after_due'],
            },
        ),
        migrations.AddField(
            model_name='feecategory',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddIndex(
            model_name='feecategory',
            index=models.Index(fields=['academic_year'], name='core_feecat_academi_403db2_idx'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='batches',
            field=models.ManyToManyField(blank=True, to='core.batch'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feecategory'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='students',
            field=models.ManyToManyField(blank=True, to='core.student'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feecategory'),
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='feereconciliation',
            name='from_academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_from', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='feereconciliation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AddField(
            model_name='feereconciliation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='feereconciliation',
            name='to_academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_to', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.feediscount'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.feecategory'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='fee_particular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.feeparticular'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='fineslab',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='fine_slab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fineslab'),
        ),
        migrations.AddIndex(
            model_name='feediscount',
            index=models.Index(fields=['tenant'], name='core_feedis_tenant__dc86ac_idx'),
        ),
        migrations.AddIndex(
            model_name='feediscount',
            index=models.Index(fields=['fee_category'], name='core_feedis_fee_cat_a72cae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feediscount',
            unique_together={('tenant', 'name', 'fee_category')},
        ),
        migrations.AddIndex(
            model_name='feeparticular',
            index=models.Index(fields=['tenant'], name='core_feepar_tenant__edf420_idx'),
        ),
        migrations.AddIndex(
            model_name='feeparticular',
            index=models.Index(fields=['fee_category'], name='core_feepar_fee_cat_b70933_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeparticular',
            unique_together={('tenant', 'name', 'fee_category')},
        ),
        migrations.AddIndex(
            model_name='feereconciliation',
            index=models.Index(fields=['tenant'], name='core_feerec_tenant__709f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='feereconciliation',
            index=models.Index(fields=['from_academic_year'], name='core_feerec_from_ac_df23e3_idx'),
        ),
        migrations.AddIndex(
            model_name='feereconciliation',
            index=models.Index(fields=['to_academic_year'], name='core_feerec_to_acad_3a24fc_idx'),
        ),
        migrations.AddIndex(
            model_name='feereconciliation',
            index=models.Index(fields=['student'], name='core_feerec_student_52ff0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feereconciliation',
            unique_together={('tenant', 'from_academic_year', 'to_academic_year', 'student')},
        ),
        migrations.AddIndex(
            model_name='fineslab',
            index=models.Index(fields=['tenant'], name='core_finesl_tenant__d82ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='fineslab',
            index=models.Index(fields=['fine_name'], name='core_finesl_fine_na_5c5a08_idx'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['tenant'], name='core_feetra_tenant__b97df2_idx'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['student'], name='core_feetra_student_15ddf8_idx'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['transaction_type'], name='core_feetra_transac_dec02a_idx'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['transaction_date'], name='core_feetra_transac_a6e2cb_idx'),
        ),
    ]
