# Generated by Django 5.2.5 on 2025-09-10 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_feediscount_feeparticular_feereconciliation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksCustomerSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quickbooks_customer_id', models.CharField(help_text='QuickBooks Customer ID', max_length=255)),
                ('customer_display_name', models.CharField(help_text='Display name in QuickBooks', max_length=255)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending Sync'), ('failed', 'Sync Failed'), ('outdated', 'Needs Update')], default='pending', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message', null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='QuickBooksFeeInvoiceSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('quickbooks_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quickbooks_doc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_status', models.CharField(choices=[('draft', 'Draft'), ('synced', 'Synced to QuickBooks'), ('failed', 'Sync Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('balance_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feecategory')),
                ('fee_particulars', models.ManyToManyField(blank=True, to='core.feeparticular')),
                ('quickbooks_customer_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quickbookscustomersync')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='QuickBooksFeePaymentSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quickbooks_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced to QuickBooks'), ('failed', 'Sync Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_generated', models.BooleanField(default=False)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('quickbooks_customer_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quickbookscustomersync')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quickbooksfeeinvoicesync')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='QuickBooksSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(choices=[('customer', 'Customer Sync'), ('invoice', 'Invoice Sync'), ('payment', 'Payment Sync'), ('bulk_sync', 'Bulk Sync Operation')], max_length=20)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('sync', 'Sync')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=10)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('quickbooks_id', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(default=dict, help_text='Additional sync details')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickBooksConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_income_account', models.CharField(blank=True, max_length=255, null=True)),
                ('default_service_item', models.CharField(blank=True, max_length=255, null=True)),
                ('default_payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_sync_customers', models.BooleanField(default=True)),
                ('auto_sync_invoices', models.BooleanField(default=True)),
                ('auto_sync_payments', models.BooleanField(default=True)),
                ('invoice_prefix', models.CharField(default='FEE', help_text='Prefix for fee invoices', max_length=10)),
                ('payment_terms_days', models.IntegerField(default=30, help_text='Default payment terms in days')),
                ('send_invoices_by_email', models.BooleanField(default=False)),
                ('send_receipts_by_email', models.BooleanField(default=True)),
                ('last_reconciliation_date', models.DateTimeField(blank=True, null=True)),
                ('reconciliation_enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_quickb_tenant__cc9f11_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quickbookscustomersync',
            index=models.Index(fields=['tenant', 'sync_status'], name='core_quickb_tenant__a1a150_idx'),
        ),
        migrations.AddIndex(
            model_name='quickbookscustomersync',
            index=models.Index(fields=['quickbooks_customer_id'], name='core_quickb_quickbo_e9e12e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quickbookscustomersync',
            unique_together={('tenant', 'quickbooks_customer_id')},
        ),
        migrations.AddIndex(
            model_name='quickbooksfeeinvoicesync',
            index=models.Index(fields=['tenant', 'sync_status'], name='core_quickb_tenant__0fb943_idx'),
        ),
        migrations.AddIndex(
            model_name='quickbooksfeeinvoicesync',
            index=models.Index(fields=['student', 'academic_year'], name='core_quickb_student_e40d02_idx'),
        ),
        migrations.AddIndex(
            model_name='quickbooksfeeinvoicesync',
            index=models.Index(fields=['quickbooks_invoice_id'], name='core_quickb_quickbo_b52156_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quickbooksfeeinvoicesync',
            unique_together={('tenant', 'quickbooks_invoice_id')},
        ),
        migrations.AddIndex(
            model_name='quickbooksfeepaymentsync',
            index=models.Index(fields=['tenant', 'sync_status'], name='core_quickb_tenant__92b59f_idx'),
        ),
        migrations.AddIndex(
            model_name='quickbooksfeepaymentsync',
            index=models.Index(fields=['student', 'payment_date'], name='core_quickb_student_4b4171_idx'),
        ),
        migrations.AddIndex(
            model_name='quickbooksfeepaymentsync',
            index=models.Index(fields=['quickbooks_payment_id'], name='core_quickb_quickbo_c3243c_idx'),
        ),
        migrations.AddIndex(
            model_name='quickbooksfeepaymentsync',
            index=models.Index(fields=['receipt_number'], name='core_quickb_receipt_220b45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quickbooksfeepaymentsync',
            unique_together={('tenant', 'quickbooks_payment_id')},
        ),
        migrations.AddIndex(
            model_name='quickbookssynclog',
            index=models.Index(fields=['tenant', 'sync_type', 'status'], name='core_quickb_tenant__604a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='quickbookssynclog',
            index=models.Index(fields=['created_at'], name='core_quickb_created_91e2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='quickbookssynclog',
            index=models.Index(fields=['object_type', 'object_id'], name='core_quickb_object__94d159_idx'),
        ),
    ]
