# Generated by Django 5.2.5 on 2025-09-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_quickbookscustomersync_quickbooksfeeinvoicesync_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbookscustomersync',
            name='quickbooks_customer_id',
            field=models.CharField(blank=True, help_text='QuickBooks Customer ID', max_length=255, null=True),
        ),
    ]
