# Generated by Django 5.2.5 on 2025-09-12 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_quickbookscustomersync_quickbooks_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSkillSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.skillset')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_sets', to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='skillset',
            index=models.Index(fields=['tenant'], name='core_skills_tenant__5ed2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='skillset',
            index=models.Index(fields=['code'], name='core_skills_code_bc0c64_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectskillset',
            index=models.Index(fields=['tenant'], name='core_subjec_tenant__4796bf_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectskillset',
            index=models.Index(fields=['subject', 'skill_set'], name='core_subjec_subject_5b4c4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectskillset',
            unique_together={('subject', 'skill_set', 'tenant')},
        ),
    ]
