# Generated by Django 5.2.5 on 2025-09-12 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_skillset_subjectskillset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='core.skill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['tenant'], name='core_skill_tenant__412143_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['skill_set'], name='core_skill_skill_s_7b4877_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['order'], name='core_skill_order_e7e777_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['tenant'], name='core_subski_tenant__1c0956_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['skill'], name='core_subski_skill_i_2d4c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['order'], name='core_subski_order_99da8a_idx'),
        ),
    ]
