# Generated by Django 5.2.5 on 2025-09-12 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_skill_subskill_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=100)),
                ('school_name', models.CharField(default='Pinewood Preparatory School', max_length=255)),
                ('school_address', models.TextField(default='235 Kasangula Road, Roma, Lusaka')),
                ('school_contact', models.CharField(default='+260 211 294802/ 291167', max_length=255)),
                ('school_email', models.EmailField(default='office@pinewoodschoolzambia.com', max_length=254)),
                ('school_website', models.URLField(default='www.pinewoodschoolzambia.com')),
                ('school_logo_url', models.URLField(blank=True, null=True)),
                ('include_exam_scores', models.BooleanField(default=True)),
                ('include_homework_assessment', models.BooleanField(default=True)),
                ('include_project_work', models.BooleanField(default=True)),
                ('include_clubs', models.BooleanField(default=True)),
                ('include_sports', models.BooleanField(default=True)),
                ('include_other_activities', models.BooleanField(default=True)),
                ('include_attendance', models.BooleanField(default=True)),
                ('include_grading_scale', models.BooleanField(default=True)),
                ('report_title', models.CharField(default='ASSESSMENT REPORT', max_length=255)),
                ('footer_quote', models.TextField(default='Pro 22:6 KJV Train up a child in the way he should go: and when he is old, he will not depart from it.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='core.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='core.batch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('header', 'Header'), ('student_info', 'Student Information'), ('exam_results', 'Exam Results'), ('homework', 'Homework Assessment'), ('project_work', 'Project Work'), ('clubs', 'Clubs'), ('sports', 'Sports'), ('other_activities', 'Other Activities'), ('attendance', 'Attendance'), ('grading_scale', 'Grading Scale'), ('footer', 'Footer')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.reporttemplate')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('club', 'Club'), ('sport', 'Sport'), ('other', 'Other Activity')], max_length=20)),
                ('activity_name', models.CharField(max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_activities', to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_data', models.JSONField(default=dict)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('html_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_error', models.TextField(blank=True, null=True)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='core.examgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='core.reporttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=100)),
                ('submission', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Weak', 'Weak'), ('Very Weak', 'Very Weak')], default='Good', max_length=20)),
                ('presentation', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Weak', 'Weak'), ('Very Weak', 'Very Weak')], default='Good', max_length=20)),
                ('effort', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Weak', 'Weak'), ('Very Weak', 'Very Weak')], default='Good', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assessments', to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assessments', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_homewo_tenant__14693a_idx'), models.Index(fields=['student'], name='core_homewo_student_6adb1c_idx'), models.Index(fields=['academic_year'], name='core_homewo_academi_5b3495_idx')],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=100)),
                ('submission', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Weak', 'Weak'), ('Very Weak', 'Very Weak')], default='Good', max_length=20)),
                ('presentation', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Weak', 'Weak'), ('Very Weak', 'Very Weak')], default='Good', max_length=20)),
                ('effort', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Weak', 'Weak'), ('Very Weak', 'Very Weak')], default='Good', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assessments', to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assessments', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_projec_tenant__bf4e06_idx'), models.Index(fields=['student'], name='core_projec_student_9562cd_idx'), models.Index(fields=['academic_year'], name='core_projec_academi_3bf726_idx')],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['tenant'], name='core_report_tenant__934b87_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['batch'], name='core_report_batch_i_5e32b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['academic_year'], name='core_report_academi_8254fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplate',
            unique_together={('tenant', 'batch', 'term', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['tenant'], name='core_report_tenant__53fb70_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['template'], name='core_report_templat_070d72_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['order'], name='core_report_order_b6158d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['tenant'], name='core_studen_tenant__ad20ab_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['student'], name='core_studen_student_98f268_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['activity_type'], name='core_studen_activit_23a7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreport',
            index=models.Index(fields=['tenant'], name='core_studen_tenant__1cfc87_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreport',
            index=models.Index(fields=['student'], name='core_studen_student_fb1e71_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreport',
            index=models.Index(fields=['template'], name='core_studen_templat_5dc202_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreport',
            index=models.Index(fields=['generation_status'], name='core_studen_generat_db4c07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentreport',
            unique_together={('student', 'template', 'exam_group')},
        ),
    ]
