# Generated by Django 5.2.5 on 2025-09-14 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_report_template_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.examgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['exam_group', 'order'],
                'indexes': [models.Index(fields=['tenant', 'exam_group'], name='core_term_tenant__61e69d_idx')],
            },
        ),
    ]
