# Generated by Django 5.2.5 on 2025-09-14 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_term_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('NOT_YET', 'Not Yet'), ('BEGINNING', 'Beginning'), ('SATISFACTORY', 'Satisfactory'), ('GOOD', 'Good')], max_length=20)),
                ('assessment_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('MOTOR_SKILLS', 'Motor Skills'), ('CONCEPTUAL_SKILLS', 'Conceptual Skills'), ('COMMUNICATION_SKILLS', 'Communication Skills'), ('CREATIVE_SKILLS', 'Creative Skills'), ('SOCIAL_SKILLS', 'Social Skills'), ('CONCENTRATION_SKILLS', 'Concentration Skills')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Description of the skill to be assessed')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('min_age_months', models.IntegerField(blank=True, help_text='Minimum age in months for this skill', null=True)),
                ('max_age_months', models.IntegerField(blank=True, help_text='Maximum age in months for this skill', null=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='SkillsAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsBasedGradingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_skills_assessed', models.IntegerField(default=0)),
                ('not_yet_count', models.IntegerField(default=0)),
                ('beginning_count', models.IntegerField(default=0)),
                ('satisfactory_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('not_yet_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('beginning_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('satisfactory_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('good_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_development_level', models.CharField(blank=True, choices=[('NOT_YET', 'Not Yet'), ('BEGINNING', 'Beginning'), ('SATISFACTORY', 'Satisfactory'), ('GOOD', 'Good')], max_length=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGradingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cumulative_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_credits_attempted', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_credits_earned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cce_scholastic_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('cce_coscholastic_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('overall_cce_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('promotion_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGradingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_elective', models.BooleanField(default=False)),
                ('internal_assessment_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Internal assessment weight %', max_digits=5)),
                ('external_assessment_weight', models.DecimalField(decimal_places=2, default=70.0, help_text='External assessment weight %', max_digits=5)),
                ('formative_assessment_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Formative assessment weight %', max_digits=5, null=True)),
                ('summative_assessment_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Summative assessment weight %', max_digits=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='cce_grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='gpa_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='icse_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='is_fail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='CoScholasticAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('LIFE_SKILLS', 'Life Skills'), ('WORK_EDUCATION', 'Work Education'), ('VISUAL_ARTS', 'Visual Arts'), ('PERFORMING_ARTS', 'Performing Arts'), ('HEALTH_PHYSICAL', 'Health & Physical Education'), ('DISCIPLINE', 'Discipline'), ('GAMES_SPORTS', 'Games & Sports')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='CoScholasticScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obtained_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coscholasticassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coscholastic_scores', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
        ),
        migrations.CreateModel(
            name='EnhancedExamScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('internal_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('external_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('internal_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('external_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('formative_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('summative_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('formative_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('summative_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('credit_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_pass', models.BooleanField(blank=True, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_scores', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_exam_scores', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='GradingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('NORMAL', 'Normal'), ('GPA', 'GPA'), ('CCE', 'CCE (Continuous Comprehensive Evaluation)'), ('ICSE', 'ICSE'), ('CWA', 'CWA (Course Weighted Average)')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gpa_scale', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum GPA (e.g., 4.0)', max_digits=3, null=True)),
                ('cce_scholastic_weight', models.DecimalField(decimal_places=2, default=70.0, help_text='Scholastic assessment weight %', max_digits=5)),
                ('cce_coscholastic_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Co-scholastic assessment weight %', max_digits=5)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='grading_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gradingtype'),
        ),
        migrations.AddIndex(
            model_name='gradinglevel',
            index=models.Index(fields=['grading_type', 'min_score'], name='core_gradin_grading_47cb2f_idx'),
        ),
        migrations.AddField(
            model_name='skillassessmentresult',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='skillitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_items', to='core.skillcategory'),
        ),
        migrations.AddField(
            model_name='skillitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='skillassessmentresult',
            name='skill_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='core.skillitem'),
        ),
        migrations.AddField(
            model_name='skillsassessment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='skillsassessment',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillsassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_assessments', to='core.student'),
        ),
        migrations.AddField(
            model_name='skillsassessment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='skillsassessment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
        migrations.AddField(
            model_name='skillassessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.skillsassessment'),
        ),
        migrations.AddField(
            model_name='skillsbasedgradingprofile',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='skillsbasedgradingprofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_grading_profiles', to='core.student'),
        ),
        migrations.AddField(
            model_name='skillsbasedgradingprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='studentgradingprofile',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='studentgradingprofile',
            name='grading_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gradingtype'),
        ),
        migrations.AddField(
            model_name='studentgradingprofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_profiles', to='core.student'),
        ),
        migrations.AddField(
            model_name='studentgradingprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='subjectgradingsettings',
            name='grading_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gradingtype'),
        ),
        migrations.AddField(
            model_name='subjectgradingsettings',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_settings', to='core.subject'),
        ),
        migrations.AddField(
            model_name='subjectgradingsettings',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddIndex(
            model_name='coscholasticassessment',
            index=models.Index(fields=['tenant', 'is_active'], name='core_coscho_tenant__8d1c39_idx'),
        ),
        migrations.AddIndex(
            model_name='coscholasticassessment',
            index=models.Index(fields=['code'], name='core_coscho_code_c3c0a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coscholasticassessment',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='coscholasticscore',
            index=models.Index(fields=['student', 'academic_year'], name='core_coscho_student_280588_idx'),
        ),
        migrations.AddIndex(
            model_name='coscholasticscore',
            index=models.Index(fields=['assessment', 'term'], name='core_coscho_assessm_89d19e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coscholasticscore',
            unique_together={('student', 'assessment', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='enhancedexamscore',
            index=models.Index(fields=['exam', 'subject'], name='core_enhanc_exam_id_5b261c_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedexamscore',
            index=models.Index(fields=['student', 'exam'], name='core_enhanc_student_c56cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedexamscore',
            index=models.Index(fields=['grade', 'is_pass'], name='core_enhanc_grade_4bf8a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enhancedexamscore',
            unique_together={('student', 'exam', 'subject')},
        ),
        migrations.AddIndex(
            model_name='gradingtype',
            index=models.Index(fields=['tenant', 'is_active'], name='core_gradin_tenant__ffed2f_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingtype',
            index=models.Index(fields=['code'], name='core_gradin_code_7a53ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradingtype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='core_skillc_tenant__d7a933_idx'),
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['code', 'display_order'], name='core_skillc_code_5f81ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillcategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='skillitem',
            index=models.Index(fields=['category', 'display_order'], name='core_skilli_categor_00d7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='skillitem',
            index=models.Index(fields=['tenant', 'is_active'], name='core_skilli_tenant__77fc05_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsassessment',
            index=models.Index(fields=['student', 'academic_year'], name='core_skills_student_aa12cc_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsassessment',
            index=models.Index(fields=['assessment_date'], name='core_skills_assessm_061e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsassessment',
            index=models.Index(fields=['is_completed'], name='core_skills_is_comp_685b46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillsassessment',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='skillassessmentresult',
            index=models.Index(fields=['assessment', 'skill_item'], name='core_skilla_assessm_c8deec_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessmentresult',
            index=models.Index(fields=['skill_item', 'level'], name='core_skilla_skill_i_5e38f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillassessmentresult',
            unique_together={('assessment', 'skill_item')},
        ),
        migrations.AddIndex(
            model_name='skillsbasedgradingprofile',
            index=models.Index(fields=['student', 'academic_year'], name='core_skills_student_d869e7_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsbasedgradingprofile',
            index=models.Index(fields=['overall_development_level'], name='core_skills_overall_43828b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillsbasedgradingprofile',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='studentgradingprofile',
            index=models.Index(fields=['student', 'academic_year'], name='core_studen_student_e96106_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgradingprofile',
            index=models.Index(fields=['cumulative_gpa'], name='core_studen_cumulat_1677a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgradingprofile',
            unique_together={('student', 'academic_year', 'grading_type')},
        ),
        migrations.AddIndex(
            model_name='subjectgradingsettings',
            index=models.Index(fields=['subject', 'grading_type'], name='core_subjec_subject_e00e3a_idx'),
        ),
    ]
