# Generated by Django 5.2.5 on 2025-09-14 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_create_grading_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('TERM', 'Term'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('half_day_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='core.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='core.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='core.term')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_attend_tenant__e396f7_idx'), models.Index(fields=['student', 'period_type'], name='core_attend_student_79dfa7_idx'), models.Index(fields=['batch', 'academic_year'], name='core_attend_batch_i_3a3f95_idx'), models.Index(fields=['period_start', 'period_end'], name='core_attend_period__aa18a0_idx')],
                'unique_together': {('student', 'period_type', 'period_start', 'period_end')},
            },
        ),
    ]
