# Generated by Django 5.2.5 on 2025-09-18 02:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_attendancesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financefee',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('color_code', models.CharField(default='#000000', max_length=7)),
                ('is_considered_present', models.BooleanField(default=True)),
                ('affects_attendance_percentage', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTimingSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_type', models.CharField(choices=[('REGULAR', 'Regular Class'), ('BREAK', 'Break'), ('LUNCH', 'Lunch Break'), ('ASSEMBLY', 'Assembly'), ('ACTIVITY', 'Activity Period')], default='REGULAR', max_length=50)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('timing_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='core.classtimingset')),
            ],
        ),
        migrations.CreateModel(
            name='EnhancedAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('period_number', models.IntegerField(blank=True, help_text='For period-wise attendance', null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('late_minutes', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('attendance_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendancelabel')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_attendance', to='core.batch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_attendance', to='core.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_name', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('CONTINUOUS', 'Continuous Assessment'), ('FORMATIVE', 'Formative Assessment'), ('SUMMATIVE', 'Summative Assessment'), ('PRACTICAL', 'Practical Assessment')], max_length=50)),
                ('weightage_percentage', models.DecimalField(decimal_places=2, help_text='Weight in final grade', max_digits=5)),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('TERM', 'Per Term'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=50)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assessments', to='core.batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_methods', to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.IntegerField(help_text='Period sequence number (1, 2, 3, etc.)')),
                ('classroom', models.CharField(blank=True, max_length=100, null=True)),
                ('is_substitution', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.batch')),
                ('class_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classtiming')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.employee')),
                ('original_employee', models.ForeignKey(blank=True, help_text='Original teacher if this is a substitution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_timetable_entries', to='core.employee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_entries', to='core.timetable')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weekday')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_name', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('CONTINUOUS', 'Continuous Assessment'), ('FORMATIVE', 'Formative Assessment'), ('SUMMATIVE', 'Summative Assessment'), ('QUIZ', 'Quiz'), ('TEST', 'Test'), ('ASSIGNMENT', 'Assignment'), ('PROJECT', 'Project'), ('PRACTICAL', 'Practical')], max_length=50)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('assessment_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.term')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_assess_tenant__f290bd_idx'), models.Index(fields=['student', 'subject', 'assessment_date'], name='core_assess_student_eb95e2_idx'), models.Index(fields=['academic_year', 'term'], name='core_assess_academi_18b112_idx'), models.Index(fields=['assessment_type', 'is_published'], name='core_assess_assessm_630ddb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attendancelabel',
            index=models.Index(fields=['tenant'], name='core_attend_tenant__4e93df_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelabel',
            index=models.Index(fields=['code'], name='core_attend_code_bd8bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelabel',
            index=models.Index(fields=['is_active'], name='core_attend_is_acti_8db00d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelabel',
            unique_together={('code', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='classtimingset',
            index=models.Index(fields=['tenant'], name='core_classt_tenant__9021d8_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimingset',
            index=models.Index(fields=['academic_year', 'is_active'], name='core_classt_academi_aa1a73_idx'),
        ),
        migrations.AddIndex(
            model_name='classperiod',
            index=models.Index(fields=['tenant'], name='core_classp_tenant__127553_idx'),
        ),
        migrations.AddIndex(
            model_name='classperiod',
            index=models.Index(fields=['timing_set', 'period_number'], name='core_classp_timing__fdf327_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classperiod',
            unique_together={('timing_set', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='enhancedattendance',
            index=models.Index(fields=['tenant'], name='core_enhanc_tenant__b6b0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedattendance',
            index=models.Index(fields=['student', 'attendance_date'], name='core_enhanc_student_8d9130_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedattendance',
            index=models.Index(fields=['batch', 'attendance_date'], name='core_enhanc_batch_i_e7dec6_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedattendance',
            index=models.Index(fields=['academic_year', 'attendance_date'], name='core_enhanc_academi_371107_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedattendance',
            index=models.Index(fields=['attendance_label'], name='core_enhanc_attenda_222cd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enhancedattendance',
            unique_together={('student', 'attendance_date', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='subjectassessment',
            index=models.Index(fields=['tenant'], name='core_subjec_tenant__b6a0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassessment',
            index=models.Index(fields=['subject', 'batch'], name='core_subjec_subject_0fed76_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassessment',
            index=models.Index(fields=['academic_year', 'is_active'], name='core_subjec_academi_96e052_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['tenant'], name='core_timeta_tenant__9ed4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['batch', 'weekday', 'period_number'], name='core_timeta_batch_i_972aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['employee', 'weekday'], name='core_timeta_employe_2f5ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['subject', 'batch'], name='core_timeta_subject_4e00b3_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['is_active', 'is_substitution'], name='core_timeta_is_acti_41b7a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('timetable', 'weekday', 'class_timing', 'batch')},
        ),
    ]
