# Generated by Django 5.2.6 on 2025-09-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_duplicate_fedena_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='regional_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
