# Generated by Django 5.2.5 on 2025-09-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_country_created_at_country_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
