# Generated by Django 5.2.5 on 2025-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_guardian_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='finerule',
            name='is_amount',
            field=models.BooleanField(default=False),
        ),
    ]
