# Generated by Django 5.2.5 on 2025-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_is_amount_to_finerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finerule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
