# Generated by Django 5.2.6 on 2025-09-23 12:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_financefee_batch_financefee_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCEGradeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scholastic_weightage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('co_scholastic_weightage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cce_grade_sets', to='core.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cce_grade_sets', to='core.batch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='CCEGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color_code', models.CharField(default='#808080', max_length=7)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('grade_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.ccegradeset')),
            ],
            options={
                'ordering': ['order', 'min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='GradebookTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('CCE', 'Continuous Comprehensive Evaluation'), ('TRADITIONAL', 'Traditional Grading'), ('CBSE', 'CBSE Pattern'), ('IB', 'International Baccalaureate'), ('CAMBRIDGE', 'Cambridge International'), ('CUSTOM', 'Custom Template')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('configuration', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='gradebook_templates', to='core.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineExamGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)])),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('max_attempts', models.IntegerField(default=1)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('show_results_immediately', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exam_groups', to='core.batch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('TIMEOUT', 'Timed Out'), ('CANCELLED', 'Cancelled')], default='STARTED', max_length=20)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exam_attempts', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.onlineexamgroup')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MSQ', 'Multiple Select'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the Blanks'), ('MATCH', 'Matching')], max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.onlineexamgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineExamOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.onlineexamquestion')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineExamAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.onlineexamattempt')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_by', to='core.onlineexamoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='core.onlineexamquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RemarkBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Performance'), ('BEHAVIOR', 'Behavior'), ('ATTENDANCE', 'Attendance'), ('PARTICIPATION', 'Class Participation'), ('IMPROVEMENT', 'Areas for Improvement'), ('STRENGTH', 'Strengths'), ('GENERAL', 'General Comments')], max_length=20)),
                ('remark_text', models.TextField()),
                ('is_positive', models.BooleanField(default=True)),
                ('frequency_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='remark_banks', to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPreviousMarks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_school_name', models.CharField(max_length=255)),
                ('board_name', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.CharField(max_length=50)),
                ('class_or_grade', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=255)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_marks', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedAssessmentRubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_points', models.PositiveIntegerField(default=100)),
                ('criteria', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rubrics', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_rubrics', to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'subject', 'is_active'], name='core_advanc_tenant__109e30_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_name', models.CharField(max_length=255)),
                ('total_students', models.PositiveIntegerField()),
                ('students_appeared', models.PositiveIntegerField()),
                ('students_passed', models.PositiveIntegerField()),
                ('average_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('highest_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lowest_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('median_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('standard_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade_distribution', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'subject', 'batch', 'academic_year'], name='core_assess_tenant__f940c9_idx'), models.Index(fields=['tenant', 'generated_at'], name='core_assess_tenant__429625_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ccegradeset',
            index=models.Index(fields=['tenant', 'batch', 'academic_year'], name='core_ccegra_tenant__1624d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ccegradeset',
            unique_together={('tenant', 'name', 'batch', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='ccegrade',
            index=models.Index(fields=['tenant', 'grade_set', 'order'], name='core_ccegra_tenant__cd5a70_idx'),
        ),
        migrations.AddIndex(
            model_name='ccegrade',
            index=models.Index(fields=['tenant', 'grade_set', 'min_percentage', 'max_percentage'], name='core_ccegra_tenant__c9df36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ccegrade',
            unique_together={('tenant', 'grade_set', 'name')},
        ),
        migrations.AddIndex(
            model_name='gradebooktemplate',
            index=models.Index(fields=['tenant', 'template_type', 'is_active'], name='core_gradeb_tenant__5ced6a_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamgroup',
            index=models.Index(fields=['tenant', 'batch', 'start_time'], name='core_online_tenant__106761_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamgroup',
            index=models.Index(fields=['tenant', 'is_active', 'is_published'], name='core_online_tenant__1dc050_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineexamgroup',
            unique_together={('tenant', 'name', 'batch')},
        ),
        migrations.AddIndex(
            model_name='onlineexamattempt',
            index=models.Index(fields=['tenant', 'student', 'exam_group'], name='core_online_tenant__cfefa5_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamattempt',
            index=models.Index(fields=['tenant', 'exam_group', 'status'], name='core_online_tenant__6b7fe3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineexamattempt',
            unique_together={('tenant', 'student', 'exam_group', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='onlineexamquestion',
            index=models.Index(fields=['tenant', 'exam_group', 'order'], name='core_online_tenant__d0a985_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineexamquestion',
            unique_together={('tenant', 'exam_group', 'order')},
        ),
        migrations.AddIndex(
            model_name='onlineexamoption',
            index=models.Index(fields=['tenant', 'question', 'order'], name='core_online_tenant__808f4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineexamoption',
            unique_together={('tenant', 'question', 'order')},
        ),
        migrations.AddIndex(
            model_name='onlineexamanswer',
            index=models.Index(fields=['tenant', 'attempt', 'question'], name='core_online_tenant__a9638c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineexamanswer',
            unique_together={('tenant', 'attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='remarkbank',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='core_remark_tenant__3ac38c_idx'),
        ),
        migrations.AddIndex(
            model_name='remarkbank',
            index=models.Index(fields=['tenant', 'frequency_used'], name='core_remark_tenant__2bc10e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpreviousmarks',
            index=models.Index(fields=['tenant', 'student', 'academic_year'], name='core_studen_tenant__b69381_idx'),
        ),
    ]
