# Generated by Django 5.2.5 on 2025-09-24 12:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_ccegradeset_ccegrade_gradebooktemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantEnquiryFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('enquiry', 'Enquiry Form Field'), ('guardian', 'Guardian Form Field'), ('office', 'Office Form Field')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('display_text', models.CharField(max_length=255)),
                ('field_type', models.IntegerField(choices=[(0, 'Text'), (1, 'Select'), (2, 'Textarea'), (3, 'Date'), (4, 'Email'), (5, 'Number'), (6, 'Phone')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_additional', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('placeholder_text', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, max_length=500, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['category', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantEnquiryFormFieldOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_value', models.CharField(max_length=255)),
                ('option_text', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.applicantenquiryformfield')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantEnquiryStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('enquired_date', models.DateField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_income', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_education', models.CharField(blank=True, max_length=100, null=True)),
                ('source_of_info', models.CharField(blank=True, max_length=100, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_email_enabled', models.BooleanField(default=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.academicyear')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to='core.employee')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.applicantenquirystage')),
            ],
            options={
                'ordering': ['-enquired_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('visit', 'Campus Visit'), ('other', 'Other')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_ups', to='core.employee')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.applicantenquiry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryStageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to='core.employee')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='core.applicantenquiry')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='core.applicantenquirystage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryStageLogNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_notes', to='core.employee')),
                ('stage_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.enquirystagelog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='applicantenquiryformfield',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='core_applic_tenant__484909_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantenquiryformfield',
            index=models.Index(fields=['tenant', 'category', 'priority'], name='core_applic_tenant__c0ea53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicantenquiryformfield',
            unique_together={('tenant', 'category', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='applicantenquiryformfieldoption',
            index=models.Index(fields=['tenant', 'form_field'], name='core_applic_tenant__95775a_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantenquirystage',
            index=models.Index(fields=['tenant', 'is_default'], name='core_applic_tenant__9dd447_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantenquirystage',
            index=models.Index(fields=['tenant', 'priority'], name='core_applic_tenant__e0a35a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicantenquirystage',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='applicantenquiry',
            index=models.Index(fields=['tenant', 'course', 'is_processed'], name='core_applic_tenant__f4e178_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantenquiry',
            index=models.Index(fields=['tenant', 'stage', 'enquired_date'], name='core_applic_tenant__b5f533_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantenquiry',
            index=models.Index(fields=['tenant', 'counselor'], name='core_applic_tenant__29a9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantenquiry',
            index=models.Index(fields=['tenant', 'is_processed', 'is_rejected'], name='core_applic_tenant__13dc50_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantenquiry',
            index=models.Index(fields=['enquiry_number'], name='core_applic_enquiry_f892d6_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiryfollowup',
            index=models.Index(fields=['tenant', 'enquiry'], name='core_enquir_tenant__a78cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiryfollowup',
            index=models.Index(fields=['tenant', 'scheduled_date', 'status'], name='core_enquir_tenant__bcbb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiryfollowup',
            index=models.Index(fields=['tenant', 'assigned_to', 'status'], name='core_enquir_tenant__fb4636_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirystagelog',
            index=models.Index(fields=['tenant', 'enquiry'], name='core_enquir_tenant__985887_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirystagelog',
            index=models.Index(fields=['tenant', 'stage'], name='core_enquir_tenant__4f1257_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirystagelognote',
            index=models.Index(fields=['tenant', 'stage_log'], name='core_enquir_tenant__ad4d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirystagelognote',
            index=models.Index(fields=['tenant', 'follow_up_date'], name='core_enquir_tenant__63a681_idx'),
        ),
    ]
