# Generated by Django 5.2.5 on 2025-09-26 01:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_applicantenquiryformfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_method', models.CharField(choices=[('student_admission', 'Student admission date'), ('batch_start', 'Batch start date')], default='batch_start', max_length=20)),
                ('mark_frequency', models.CharField(choices=[('open', 'Open'), ('lock', 'Lock')], default='open', max_length=10)),
                ('enable_custom_attendance', models.BooleanField(default=True)),
                ('lock_after_days', models.IntegerField(default=7, help_text='Days after which attendance gets locked')),
                ('allow_admin_unlock', models.BooleanField(default=True)),
                ('send_absence_notifications', models.BooleanField(default=True)),
                ('notification_threshold', models.IntegerField(default=3, help_text='Send notification after X consecutive absences')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
                'indexes': [models.Index(fields=['tenant'], name='core_attend_tenant__33eec6_idx')],
            },
        ),
    ]
