# Generated by Django 5.2.6 on 2025-09-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_attendance_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.term'),
        ),
    ]
