# Generated by Django 5.2.6 on 2025-09-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_grading_scale_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectskillset',
            options={'ordering': ['display_order', 'skill_set__name']},
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='core_activi_tenant__727c1a_idx',
            old_name='core_activi_tenant__profile_idx',
        ),
        migrations.RenameIndex(
            model_name='activityassessment',
            new_name='core_activi_tenant__538477_idx',
            old_name='core_activi_tenant__sss_term_idx',
        ),
        migrations.RenameIndex(
            model_name='activitygrade',
            new_name='core_activi_tenant__f4fcce_idx',
            old_name='core_activi_tenant__student_idx',
        ),
        migrations.RenameIndex(
            model_name='activitygrade',
            new_name='core_activi_activit_55c08d_idx',
            old_name='core_activi_assess__student_idx',
        ),
        migrations.RenameIndex(
            model_name='activityprofile',
            new_name='core_activi_tenant__d5ec39_idx',
            old_name='core_activi_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='gradevalue',
            new_name='core_gradev_tenant__233d57_idx',
            old_name='core_gradev_tenant__scale_idx',
        ),
        migrations.RenameIndex(
            model_name='gradevalue',
            new_name='core_gradev_grading_c65e6a_idx',
            old_name='core_gradev_scale__order_idx',
        ),
        migrations.RenameIndex(
            model_name='gradingscale',
            new_name='core_gradin_tenant__693973_idx',
            old_name='core_gradin_tenant__active_idx',
        ),
        migrations.RenameIndex(
            model_name='gradingscale',
            new_name='core_gradin_code_99c8b1_idx',
            old_name='core_gradin_code_idx',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='default_grading_scale',
        ),
        migrations.AlterField(
            model_name='activity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='activityassessment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='activitygrade',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='gradevalue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='no_exams',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use skill_sets relationship instead. Kept for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='subjectskillset',
            name='grading_profile',
            field=models.ForeignKey(blank=True, help_text='LEGACY: Old grading profile. Use grading_scale instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_skill_sets', to='core.gradinglevel'),
        ),
        migrations.AddIndex(
            model_name='subjectskillset',
            index=models.Index(fields=['subject', 'is_active', 'display_order'], name='core_subjec_subject_62d026_idx'),
        ),
    ]
