# Generated by Django 5.2.6 on 2025-09-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_exam_grading_scale'),
        ('core', '0040_alter_subjectskillset_options_and_more'),
    ]

    operations = [
    ]
