# Generated by Django 5.2.5 on 2025-10-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20250930_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional display name for the exam', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(blank=True, help_text='Exam code like "EM2"', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(blank=True, help_text='Exam name like "EXAMINATION/TEST MARK"', max_length=255, null=True),
        ),
    ]
