# Generated by Django 5.2.15 on 2026-06-05 09:51

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_school_logo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.models.public_storage, upload_to=core.models.school_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'])]),
        ),
    ]
