# Generated by Django 5.2.15 on 2026-06-05 10:36

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_school_logo_public_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo_secondary',
            field=models.ImageField(blank=True, null=True, storage=core.models.public_storage, upload_to=core.models.school_logo_secondary_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'])]),
        ),
    ]
