# Generated by Django 5.2.15 on 2026-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_reporttemplate_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='layout_type',
            field=models.CharField(choices=[('SKILLS', 'Skills Checklist (Beginners / Reception)'), ('SIMPLE_ACADEMIC', 'Simple Academic (Grade 1–2)'), ('FULL_ACADEMIC', 'Full Academic (Grade 3–7)')], default='FULL_ACADEMIC', help_text='Controls which PDF template structure is used for this report', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='signature_title',
            field=models.CharField(default='Head of School', help_text='Title shown under the signature image on the report card', max_length=100),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='primary_color',
            field=models.CharField(default='#5a9e2f', help_text='Hex color for report card headers and accents', max_length=7),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='section_order',
            field=models.JSONField(default=list, help_text='Ordered section-group keys for PDF rendering'),
        ),
    ]
