# Generated by Django 5.2.15 on 2026-06-06 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_reporttemplate_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='grading_scale',
            field=models.ForeignKey(blank=True, help_text='Leave blank to use per-batch GradingLevel or the layout default scale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to='core.gradingscale'),
        ),
    ]
