# Generated by Django 5.2.15 on 2026-06-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_reporttemplate_grading_scale'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreport',
            unique_together={('tenant', 'student', 'template', 'exam_group')},
        ),
    ]
