# Generated by Django 5.2.15 on 2026-06-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_studentreport_unique_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('other', 'Other')], default='cash', help_text='Payment method used', max_length=20),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('other', 'Other')], default='cash', help_text='Method used for this transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
