# Generated by Django 5.2.15 on 2026-06-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_batch_class_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='employee',
            field=models.ForeignKey(help_text='Primary class teacher (kept in sync with the first class teacher)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.employee'),
        ),
    ]
