# Generated by Django 5.2.15 on 2026-06-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_exam_assessment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this fee collection belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_collections', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this fee ledger row belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_transactions', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='financefee',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this fee charge belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_fees', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this transaction belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transactions', to='core.academicyear'),
        ),
        migrations.AddIndex(
            model_name='feecollection',
            index=models.Index(fields=['tenant', 'academic_year'], name='core_feecol_tenant__4eeee9_idx'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['tenant', 'student', 'academic_year'], name='core_feetra_tenant__e261d5_idx'),
        ),
        migrations.AddIndex(
            model_name='financefee',
            index=models.Index(fields=['tenant', 'student', 'academic_year'], name='core_financ_tenant__d20c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['tenant', 'academic_year', 'transaction_date'], name='core_financ_tenant__5b304c_idx'),
        ),
    ]
