# Generated by Django 5.2.15 on 2026-06-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_backfill_finance_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quickbooksfeepaymentsync',
            unique_together={('tenant', 'quickbooks_payment_id')},
        ),
        migrations.AddField(
            model_name='quickbooksfeeinvoicesync',
            name='finance_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qb_invoice_syncs', to='core.financefee'),
        ),
        migrations.AddField(
            model_name='quickbooksfeepaymentsync',
            name='fee_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qb_payment_syncs', to='core.feetransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='quickbooksfeepaymentsync',
            unique_together={('tenant', 'fee_transaction'), ('tenant', 'quickbooks_payment_id')},
        ),
    ]
