# Generated by Django 5.2.15 on 2026-06-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_skillitem_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employeecategory'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employeedepartment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employeegrade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employeeposition'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_home_country', to='core.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_office_country', to='core.country'),
        ),
        migrations.AlterField(
            model_name='extendedadmissionapplication',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.academicyear'),
        ),
        migrations.AlterField(
            model_name='extendedadmissionapplication',
            name='course_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
