# Generated by Django 5.2.15 on 2026-06-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_teachercomment_signature_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teachercomment',
            new_name='core_teache_tenant__7a5b6d_idx',
            old_name='core_teache_tenant__examgr_idx',
        ),
    ]
