# Generated by Django 5.2.15 on 2026-06-29 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_skillsteachercomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skillsteachercomment',
            new_name='core_skills_tenant__55010f_idx',
            old_name='core_skills_tenant__batch__term_idx',
        ),
        migrations.AlterField(
            model_name='skillsteachercomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
    ]
