# Generated by Django 5.2.15 on 2026-07-03 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_backfill_family_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookscustomersync',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickbookscustomersync',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksfeeinvoicelinesync',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickbooksfeeinvoicelinesync',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksfeeinvoicesync',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickbooksfeeinvoicesync',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksfeepaymentsync',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickbooksfeepaymentsync',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuickBooksRealmMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realm_id', models.CharField(max_length=255, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_realm_mappings', to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
