# Generated by Django 5.2.15 on 2026-07-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_quickbookscustomersync_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfeecategory',
            name='is_derived',
            field=models.BooleanField(default=False, help_text="True if amount is auto-maintained as the sum of the category's FeeParticular amounts"),
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='fine_slab',
            field=models.ForeignKey(blank=True, help_text='Any one row of the fine slab ladder (grouped by fine_name) to apply after due_date', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_particulars', to='core.fineslab'),
        ),
    ]
