# Generated by Django 5.2.15 on 2026-07-05 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_backfill_batch_fee_category_derived'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='revocation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_waivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
