# Generated by Django 5.2.15 on 2026-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_feewaiver_revoke_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingscale',
            name='scale_type',
            field=models.CharField(choices=[('LETTER', 'Letter Grades (A, B, C, D, E)'), ('DESCRIPTIVE', 'Descriptive (Very Good, Good, Satisfactory, Weak)'), ('NUMERIC', 'Numeric Marks'), ('LEVEL', 'Skill Levels (Not Yet, Beginning, Satisfactory, Good)'), ('BINARY', 'Pass/Fail or Y/N'), ('CUSTOM', 'Custom Grade Set')], help_text='Type of grading scale', max_length=20),
        ),
    ]
