# Generated by Django 5.2.15 on 2026-07-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_gradingscale_scale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinvoiceline',
            name='finance_fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_invoice_line', to='core.financefee'),
        ),
        migrations.AlterField(
            model_name='quickbooksfeeinvoicelinesync',
            name='finance_fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qb_invoice_line_syncs', to='core.financefee'),
        ),
    ]
