# Generated by Django 5.2.15 on 2026-07-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_familyinvoiceline_finance_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='working_days',
            field=models.JSONField(default=list, help_text='Weekday integers (0=Mon, 6=Sun) when school operates'),
        ),
        migrations.AddField(
            model_name='event',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.academicyear'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['academic_year', 'is_holiday'], name='core_event_academi_018fcd_idx'),
        ),
    ]
