# Generated by Django 5.2.15 on 2026-07-08 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_add_school_calendar_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchExamTypeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_traditional_exams', models.BooleanField(default=True, help_text='Enable traditional written exams')),
                ('enable_skills_assessment', models.BooleanField(default=True, help_text='Enable skills assessment tests')),
                ('enable_activities', models.BooleanField(default=False, help_text='Enable activities (clubs, sports, projects)')),
                ('enable_classwork', models.BooleanField(default=True, help_text='Enable classwork assessment')),
                ('enable_tests', models.BooleanField(default=True, help_text='Enable short tests')),
                ('enable_homework', models.BooleanField(default=True, help_text='Enable homework assessment')),
                ('enabled_custom_exam_types', models.JSONField(blank=True, default=list, help_text='List of additional custom exam type names that are enabled for this batch')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_config', to='core.batch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_batche_tenant__417ed9_idx'), models.Index(fields=['batch'], name='core_batche_batch_i_89388c_idx')],
            },
        ),
    ]
