# Generated by Django 5.2.15 on 2026-07-09 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_timetable_classroom_and_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeApplicabilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('all', 'All Students'), ('admission_number', 'By Admission Number'), ('student_category', 'By Student Category'), ('batch', 'By Batch'), ('individual_student', 'Individual Student')], max_length=20)),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.batch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
                ('student_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='feediscount',
            name='applicability_rule',
            field=models.ForeignKey(blank=True, help_text='Rule determining which students this discount applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_discounts', to='core.feeapplicabilityrule'),
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='applicability_rule',
            field=models.ForeignKey(blank=True, help_text='Rule determining which students this particular applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_particulars', to='core.feeapplicabilityrule'),
        ),
        migrations.AddIndex(
            model_name='feeapplicabilityrule',
            index=models.Index(fields=['tenant'], name='core_feeapp_tenant__a410e0_idx'),
        ),
        migrations.AddIndex(
            model_name='feeapplicabilityrule',
            index=models.Index(fields=['rule_type'], name='core_feeapp_rule_ty_f639cd_idx'),
        ),
    ]
