# Generated by Django 5.2.15 on 2026-07-09 07:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


def add_classroom_safe(apps, schema_editor):
    """Idempotent add classroom field - only if it doesn't already exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM information_schema.columns
                WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
                AND table_name='core_timetable' AND column_name='classroom'
            )
        """)
        if not cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE core_timetable ADD COLUMN classroom varchar(100) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_feeapplicabilityrule_feediscount_applicability_rule_and_more'),
    ]

    operations = [
        migrations.RunPython(add_classroom_safe, migrations.RunPython.noop),
        migrations.CreateModel(
            name='FeeMasterDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='feediscount',
            name='master_discount',
            field=models.ForeignKey(blank=True, help_text='Link to master template if instantiated from one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='core.feemasterdiscount'),
        ),
        migrations.CreateModel(
            name='FeeMasterParticular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='master_particular',
            field=models.ForeignKey(blank=True, help_text='Link to master template if instantiated from one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='particulars', to='core.feemasterparticular'),
        ),
        migrations.AddIndex(
            model_name='feemasterdiscount',
            index=models.Index(fields=['tenant'], name='core_feemas_tenant__5ea811_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feemasterdiscount',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='feemasterparticular',
            index=models.Index(fields=['tenant'], name='core_feemas_tenant__ee8572_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feemasterparticular',
            unique_together={('tenant', 'name')},
        ),
    ]
