# Generated by Django 5.2.15 on 2026-07-09 07:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


def add_classroom_safe(apps, schema_editor):
    """Idempotent add classroom field - only if it doesn't already exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM information_schema.columns
                WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
                AND table_name='core_timetable' AND column_name='classroom'
            )
        """)
        if not cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE core_timetable ADD COLUMN classroom varchar(100) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_timetable_classroom_feemasterdiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', help_text='Collection workflow status: draft → published → closed/archived', max_length=20),
        ),
        migrations.AddField(
            model_name='financefee',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Unique invoice identifier (generated when collection is published)', max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(add_classroom_safe, migrations.RunPython.noop),
        migrations.CreateModel(
            name='FinanceFeeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particular_name', models.CharField(help_text='Snapshot of FeeParticular.name at generation time', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Snapshot of FeeParticular.amount at generation time', max_digits=15)),
                ('fee_particular', models.ForeignKey(blank=True, help_text='Original fee particular (for provenance; may be deleted later)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.feeparticular')),
                ('finance_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.financefee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_financ_tenant__e72fee_idx'), models.Index(fields=['finance_fee'], name='core_financ_finance_3c4e2f_idx')],
            },
        ),
    ]
