# Generated by Django 5.2.15 on 2026-07-09 07:14

from django.db import migrations, models


def add_classroom_safe(apps, schema_editor):
    """Idempotent add classroom field - only if it doesn't already exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM information_schema.columns
                WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
                AND table_name='core_timetable' AND column_name='classroom'
            )
        """)
        if not cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE core_timetable ADD COLUMN classroom varchar(100) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_feecollection_status_financefee_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeparticular',
            name='creation_type',
        ),
        migrations.RunPython(add_classroom_safe, migrations.RunPython.noop),
    ]
