# Generated by Django 5.2.15 on 2026-07-09 07:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def add_classroom_safe(apps, schema_editor):
    """Idempotent add classroom field - only if it doesn't already exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM information_schema.columns
                WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
                AND table_name='core_timetable' AND column_name='classroom'
            )
        """)
        if not cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE core_timetable ADD COLUMN classroom varchar(100) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_remove_feeparticular_creation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feediscount',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Discount is only applied on/after this date', null=True),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Discount is no longer applied after this date', null=True),
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Particular is only applied on/after this date', null=True),
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Particular is no longer applied after this date', null=True),
        ),
        migrations.RunPython(add_classroom_safe, migrations.RunPython.noop),
        migrations.CreateModel(
            name='FeeAmountChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_amount_changes', to=settings.AUTH_USER_MODEL)),
                ('fee_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_changes', to='core.feediscount')),
                ('fee_particular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_changes', to='core.feeparticular')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_feeamo_tenant__7b369a_idx'), models.Index(fields=['fee_particular'], name='core_feeamo_fee_par_c1bdfc_idx'), models.Index(fields=['fee_discount'], name='core_feeamo_fee_dis_eeb088_idx'), models.Index(fields=['changed_at'], name='core_feeamo_changed_6d12ec_idx')],
            },
        ),
    ]
