# Generated by Django 5.2.15 on 2026-07-09 07:21

import django.db.models.deletion
from django.db import migrations, models


def add_classroom_safe(apps, schema_editor):
    """Idempotent add classroom field - only if it doesn't already exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM information_schema.columns
                WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
                AND table_name='core_timetable' AND column_name='classroom'
            )
        """)
        if not cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE core_timetable ADD COLUMN classroom varchar(100) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_feediscount_effective_date_feediscount_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('termly', 'Termly'), ('yearly', 'Yearly')], default='one_time', help_text='Collection recurrence pattern', max_length=20),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='late_fee_rule',
            field=models.ForeignKey(blank=True, help_text='Late fee rule for this collection (overrides particular-level rules)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collections', to='core.fineslab'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='next_generation_date',
            field=models.DateField(blank=True, help_text='When the next recurrence should be generated (for recurring collections)', null=True),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='parent_collection',
            field=models.ForeignKey(blank=True, help_text='Parent collection if this is a recurring instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='core.feecollection'),
        ),
        migrations.RunPython(add_classroom_safe, migrations.RunPython.noop),
    ]
