# Generated by Django 5.2.15 on 2026-07-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_user_password_change_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_collected', to='core.employee'),
        ),
    ]
