# Generated by Django 5.2.15 on 2026-07-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_feetransaction_collected_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
