# Generated by Django 5.2.15 on 2026-07-17 03:33

from django.db import migrations, models
from django.db.models import Q


def backfill_teaching_staff(apps, schema_editor):
    """Heuristic one-time backfill: flag employees who already look like
    teachers based on free-form job_title/category/position text, since no
    tenant seeded a structured "Teacher" designation before this field existed.
    """
    Employee = apps.get_model('core', 'Employee')
    Employee.objects.filter(
        Q(job_title__icontains='teach')
        | Q(employee_category__name__icontains='teach')
        | Q(employee_position__name__icontains='teach')
    ).update(is_teaching_staff=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_student_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_teaching_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_teaching_staff'], name='core_employ_tenant__e28a2f_idx'),
        ),
        migrations.RunPython(backfill_teaching_staff, noop_reverse),
    ]
