# Generated by Django 5.2.15 on 2026-07-17 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_employee_is_teaching_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkingDaySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_days', models.JSONField(default=list, help_text='Weekday integers (0=Mon, 6=Sun) employees are expected to work')),
                ('default_daily_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('half_day_hours_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Employee Working Day Settings',
                'verbose_name_plural': 'Employee Working Day Settings',
                'indexes': [models.Index(fields=['tenant'], name='core_employ_tenant__1ea05d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('default_annual_days', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_leavet_tenant__ba6c1a_idx')],
            },
        ),
    ]
