# Generated by Django 5.2.15 on 2026-07-17 04:52
# Hand-edited: the autodetector produced an AddField(leave_type_legacy) +
# AlterField(leave_type CharField -> ForeignKey) pair, which would both lose
# the existing free-text leave_type data (Postgres can't cast "Sick Leave"
# text into a FK column) and likely fail outright. Replaced with a proper
# RenameField (preserves the column/data) followed by a fresh FK AddField,
# plus a data migration to backfill `status` and best-effort-match legacy
# text to LeaveType rows.

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_leave_status_and_type(apps, schema_editor):
    EmployeeLeave = apps.get_model('core', 'EmployeeLeave')
    LeaveType = apps.get_model('core', 'LeaveType')

    for leave in EmployeeLeave.objects.all().iterator():
        leave.status = 'approved' if leave.is_approved else 'pending'

        legacy_text = (leave.leave_type_legacy or '').strip()
        if legacy_text:
            leave_type, _ = LeaveType.objects.get_or_create(
                tenant_id=leave.tenant_id,
                name__iexact=legacy_text,
                defaults={'name': legacy_text, 'default_annual_days': 0},
            )
            leave.leave_type_id = leave_type.id

        leave.save(update_fields=['status', 'leave_type'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_employeeworkingdaysettings_leavetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('half_day', 'Half Day'), ('holiday', 'Holiday')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employeeleave',
            old_name='leave_type',
            new_name='leave_type_legacy',
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to='core.leavetype'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employeeleave',
            index=models.Index(fields=['tenant', 'status'], name='core_employ_tenant__ac7666_idx'),
        ),
        migrations.RunPython(backfill_leave_status_and_type, noop_reverse),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['tenant'], name='core_employ_tenant__4bb635_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['tenant', 'date'], name='core_employ_tenant__fd8206_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['employee', 'date'], name='core_employ_employe_0dc274_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'date')},
        ),
    ]
