# Generated by Django 5.2.15 on 2026-07-17 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_employeeattendance_employeeleave_leave_type_legacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('category_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Basic Pay')], default='fixed', max_length=20)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_basic_pay', models.BooleanField(default=False, help_text='The one earning category used as the percentage base for this tenant')),
                ('taxable', models.BooleanField(default=False, help_text='Display-only flag; no tax calculation is applied')),
                ('status', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_pay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('payroll_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payrollgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollGroupComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('override_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('payroll_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payrollcategory')),
                ('payroll_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.payrollgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_group_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('basic_pay_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='generated', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payslips', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='core.employee')),
                ('generated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to=settings.AUTH_USER_MODEL)),
                ('payroll_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payrollgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name_snapshot', models.CharField(max_length=255)),
                ('category_type_snapshot', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.IntegerField(default=0)),
                ('payroll_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payrollcategory')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.payslip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PayslipReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_company_logo', models.BooleanField(default=True)),
                ('show_bank_details', models.BooleanField(default=True)),
                ('show_leave_balance', models.BooleanField(default=False)),
                ('show_ytd_earnings', models.BooleanField(default=False)),
                ('show_employee_photo', models.BooleanField(default=False)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Payslip Settings',
                'verbose_name_plural': 'Payslip Settings',
            },
        ),
        migrations.AddIndex(
            model_name='payrollcategory',
            index=models.Index(fields=['tenant'], name='core_payrol_tenant__8196c0_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollgroup',
            index=models.Index(fields=['tenant'], name='core_payrol_tenant__d80c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayrollprofile',
            index=models.Index(fields=['tenant'], name='core_employ_tenant__668500_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollgroupcomponent',
            index=models.Index(fields=['tenant'], name='core_payrol_tenant__e73409_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollgroupcomponent',
            unique_together={('payroll_group', 'payroll_category')},
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant'], name='core_paysli_tenant__14669b_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', 'status'], name='core_paysli_tenant__fb0ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'period_start'], name='core_paysli_employe_4fffb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='paysliplineitem',
            index=models.Index(fields=['tenant'], name='core_paysli_tenant__21cce6_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipreporttemplate',
            index=models.Index(fields=['tenant'], name='core_paysli_tenant__9f35fe_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipsettings',
            index=models.Index(fields=['tenant'], name='core_paysli_tenant__11aa18_idx'),
        ),
    ]
