# Generated by Django 5.2.15 on 2026-07-17 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_payrollcategory_payrollgroup_employeepayrollprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReceiptSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, help_text='Employee whose name prints as Cashier on fee receipts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Fee Receipt Settings',
                'verbose_name_plural': 'Fee Receipt Settings',
                'indexes': [models.Index(fields=['tenant'], name='core_feerec_tenant__70e2fb_idx')],
            },
        ),
    ]
