# Generated by Django 5.2.15 on 2026-07-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_feereceiptsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='authorized_pickup_persons',
            field=models.TextField(blank=True, help_text='Person(s) authorised to collect the child from school'),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='declaration_signature_name',
            field=models.CharField(blank=True, help_text='Typed full name of parent/guardian as a digital signature', max_length=200),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='emergency_contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='guardian1_area_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='guardian1_flat_block_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='guardian1_house_plot_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='guardian1_road_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='guardian2_area_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='guardian2_flat_block_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='guardian2_house_plot_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='guardian2_road_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='home_language',
            field=models.CharField(blank=True, help_text="Language most commonly spoken in the child's home", max_length=100),
        ),
        migrations.AddField(
            model_name='extendedadmissionapplication',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Name by which the child should be addressed in school', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissiondocument',
            name='document_type',
            field=models.CharField(choices=[('immunization_record', 'Under 5 Card (Immunization Record)'), ('birth_certificate', 'Birth Certificate'), ('utility_bill', 'Utility Bill (Proof of Residence)'), ('parent1_id', 'National Registration Card - Parent 1'), ('parent2_id', 'National Registration Card - Parent 2'), ('student_photo', 'Student Passport Photo'), ('passport_photo_1', 'Passport Photo 1'), ('passport_photo_2', 'Passport Photo 2'), ('academic_transcript', 'Academic Transcript'), ('other', 'Other Document')], max_length=50),
        ),
    ]
