# Generated by Django 5.2.15 on 2026-07-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_extendedadmissionapplication_authorized_pickup_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceiptsettings',
            name='next_receipt_number',
            field=models.PositiveIntegerField(default=1, help_text='Next sequential number to allocate for a receipt (auto-increments)'),
        ),
        migrations.AddField(
            model_name='feereceiptsettings',
            name='receipt_prefix',
            field=models.CharField(default='PW', help_text='Prefix for auto-generated sequential receipt numbers, e.g. PW7022', max_length=10),
        ),
    ]
