# Generated by Django 5.2.15 on 2026-07-18 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_feereceiptsettings_next_receipt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesSaveCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ratings_saved_at', models.DateTimeField(blank=True, null=True)),
                ('activities_saved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_checkpoints', to='core.batch')),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_checkpoints', to='core.examgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'unique_together': {('tenant', 'batch', 'exam_group')},
            },
        ),
    ]
