# Generated by Django 5.2.15 on 2026-07-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_teachercomment_class_teacher'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classteacherassignment',
            new_name='core_classt_tenant__3e0403_idx',
            old_name='core_classtte_tenant_batch_idx',
        ),
        migrations.RenameIndex(
            model_name='classteacherassignment',
            new_name='core_classt_tenant__050ab0_idx',
            old_name='core_classtte_tenant_stud_idx',
        ),
        migrations.RenameIndex(
            model_name='classteacherassignment',
            new_name='core_classt_tenant__2f4a01_idx',
            old_name='core_classtte_tenant_empl_idx',
        ),
    ]
