# Generated by Django 5.2.15 on 2026-07-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_rename_core_classtte_tenant_batch_idx_core_classt_tenant__3e0403_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillsteachercomment',
            unique_together={('tenant', 'student', 'batch', 'term', 'class_teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='teachercomment',
            unique_together={('tenant', 'student', 'exam_group', 'class_teacher')},
        ),
    ]
