# Generated by Django 5.2.15 on 2026-07-21 10:17

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_teacher_comment_class_teacher_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Signatory's name, e.g. 'Mrs. Jane Mwansa'", max_length=150)),
                ('title', models.CharField(default='Head of School', help_text='Title printed under the signature image on report cards', max_length=100)),
                ('section_label', models.CharField(blank=True, help_text="Optional descriptive grouping, e.g. 'Lower Primary' — informational only (mirrors Course.section_name), not linked to any batch/course", max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=core.models.public_storage, upload_to=core.models.school_signature_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
                ('is_default', models.BooleanField(default=False, help_text="Used by report templates that don't specify a signature of their own")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-is_default', 'title', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolsignature',
            index=models.Index(fields=['tenant'], name='core_school_tenant__689950_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolsignature',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='unique_default_school_signature_per_tenant'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='report_signature',
            field=models.ForeignKey(blank=True, help_text='Leave blank to use the tenant default signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to='core.schoolsignature'),
        ),
    ]
