# Generated by Django 5.2.15 on 2026-08-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_collapse_teacher_comment_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('TEXTBOOK', 'Textbook'), ('STORYBOOK', 'Storybook'), ('TEACHER_RESOURCE', "Teacher's Resource Book"), ('REFERENCE', 'Reference'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='school_level',
            field=models.CharField(choices=[('LOWER_SCHOOL', 'Lower School'), ('UPPER_SCHOOL', 'Upper School'), ('ALL', 'All Levels')], default='ALL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_type'], name='core_book_book_ty_90abfb_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['school_level'], name='core_book_school__bdd435_idx'),
        ),
    ]
