# Generated by Django 5.2.15 on 2026-08-17 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_paymentagreement_and_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentagreement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='paymentagreementinstallment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentagreementinstallment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='paymentagreementpaymentrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentagreementpaymentrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AddIndex(
            model_name='paymentagreement',
            index=models.Index(fields=['tenant'], name='core_paymen_tenant__39eceb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreement',
            index=models.Index(fields=['student'], name='core_paymen_student_f2dc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreement',
            index=models.Index(fields=['status'], name='core_paymen_status_f31f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreement',
            index=models.Index(fields=['created_at'], name='core_paymen_created_8abfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreementinstallment',
            index=models.Index(fields=['tenant'], name='core_paymen_tenant__6b01f5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreementinstallment',
            index=models.Index(fields=['agreement'], name='core_paymen_agreeme_6a46b2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreementinstallment',
            index=models.Index(fields=['due_date'], name='core_paymen_due_dat_0e476b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreementpaymentrecord',
            index=models.Index(fields=['tenant'], name='core_paymen_tenant__8d4054_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreementpaymentrecord',
            index=models.Index(fields=['agreement'], name='core_paymen_agreeme_23d6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentagreementpaymentrecord',
            index=models.Index(fields=['payment_date'], name='core_paymen_payment_a58dbc_idx'),
        ),
    ]
