# Generated by Django 5.2.15 on 2026-08-23 05:06

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_add_report_zip_job_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportzipjob',
            new_name='core_report_tenant__f16353_idx',
            old_name='core_reportz_tenant__6d8c0e_idx',
        ),
        migrations.RenameIndex(
            model_name='reportzipjob',
            new_name='core_report_tenant__6e1690_idx',
            old_name='core_reportz_tenant__3f2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='reportzipjob',
            new_name='core_report_tenant__f2321d_idx',
            old_name='core_reportz_tenant__e4c9d2_idx',
        ),
        migrations.AlterField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to_news_documents, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), core.models.validate_news_document_size]),
        ),
        migrations.AlterField(
            model_name='reportzipjob',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_zip_job_expiry, help_text='When this job and its ZIP file should be cleaned up'),
        ),
        migrations.AlterField(
            model_name='reportzipjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
    ]
