# Generated by Django 5.2.15 on 2026-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_school_operations_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
