# Generated by Django 5.2.15 on 2026-08-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_book_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term this billing run belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_collections', to='core.term'),
        ),
    ]
