# Generated by Django 5.2.15 on 2026-09-01 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_backfill_book_library'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='book',
            new_name='core_book_library_c1f2a1_idx',
            old_name='core_book_library_c4e7f2_idx',
        ),
        migrations.RenameIndex(
            model_name='library',
            new_name='core_librar_tenant__49ede6_idx',
            old_name='core_librar_tenant_e56a4b_idx',
        ),
        migrations.RenameIndex(
            model_name='librarystaff',
            new_name='core_librar_tenant__6c665b_idx',
            old_name='core_librar_tenant_7f9e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='librarystaff',
            new_name='core_librar_employe_805a25_idx',
            old_name='core_librar_employ_8e2f3b_idx',
        ),
        migrations.RenameIndex(
            model_name='librarystaff',
            new_name='core_librar_library_35afe8_idx',
            old_name='core_librar_library_9c3d4f_idx',
        ),
        migrations.AlterField(
            model_name='library',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='library',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
        migrations.AlterField(
            model_name='librarystaff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='librarystaff',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
    ]
