# Generated by Django 5.2.15 on 2026-09-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_batchfeecategorystudent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batchfeecategorystudent',
            new_name='core_batchf_tenant__7ed330_idx',
            old_name='core_batchf_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='batchfeecategorystudent',
            new_name='core_batchf_batch_f_8c81b2_idx',
            old_name='core_batchf_batch_f_idx',
        ),
        migrations.AlterField(
            model_name='batchfeecategorystudent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school'),
        ),
    ]
