# Generated by Django 5.2.15 on 2026-09-02 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_rename_core_batchf_tenant_idx_core_batchf_tenant__7ed330_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='core.batch'),
        ),
        migrations.AddField(
            model_name='sms',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='core.guardian'),
        ),
        migrations.AddField(
            model_name='sms',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sms',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='sms',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='sms',
            index=models.Index(fields=['tenant', 'batch'], name='core_sms_tenant__d44dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='sms',
            index=models.Index(fields=['tenant', 'status'], name='core_sms_tenant__2b3e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='sms',
            index=models.Index(fields=['tenant', 'created_at'], name='core_sms_tenant__13c213_idx'),
        ),
    ]
