# Generated by Django 5.2.15 on 2026-09-02 07:13

from django.db import migrations


def backfill_status(apps, schema_editor):
    Sms = apps.get_model('core', 'Sms')
    Sms.objects.filter(is_sent=True).update(status='sent')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_sms_batch_sms_error_message_sms_guardian_sms_sent_at_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_status),
    ]
