# Generated by Django 5.2.15 on 2026-09-02 09:59

from django.db import migrations, models
import django.db.models.deletion


def check_academic_year_populated(apps, schema_editor):
    """Pre-flight check: verify no NULL academic_year rows before removing exam_group."""
    Term = apps.get_model('core', 'Term')
    null_count = Term.objects.filter(academic_year__isnull=True).count()
    if null_count > 0:
        raise RuntimeError(
            f"Cannot remove exam_group field: {null_count} Term rows still have NULL academic_year. "
            "Run Phase 2 consolidation (consolidate_terms.py --execute) first."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_term_academic_year'),
    ]

    operations = [
        # Pre-flight check: verify academic_year is populated before proceeding
        migrations.RunPython(check_academic_year_populated, migrations.RunPython.noop),

        # Remove the old exam_group field (no longer needed; academic_year is now canonical)
        migrations.RemoveField(
            model_name='term',
            name='exam_group',
        ),

        # Make academic_year non-nullable (all rows should be populated by Phase 2)
        migrations.AlterField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='terms_by_year',
                to='core.academicyear',
            ),
        ),

        # Add unique constraint: (tenant, academic_year, name) per year
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('tenant', 'academic_year', 'name')},
        ),

        # Remove old index and update Meta.ordering
        migrations.AlterModelOptions(
            name='term',
            options={
                'ordering': ['academic_year', 'order'],
                'unique_together': {('tenant', 'academic_year', 'name')},
            },
        ),

        # Remove the old exam_group+tenant index
        migrations.RemoveIndex(
            model_name='term',
            name='core_term_tenant__61e69d_idx',
        ),
    ]
