# Generated by Django 5.2.15 on 2026-09-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_remove_exam_group_add_unique_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='term',
            new_name='core_term_tenant__f0d6f0_idx',
            old_name='core_term_tenant_ac_idx',
        ),
    ]
