# Generated by Django 5.2.15 on 2026-09-03 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_rename_core_term_tenant_ac_idx_core_term_tenant__f0d6f0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='fee_note_early_bird_discount_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='fee_note_early_bird_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shown only when the early-bird discount is enabled.', max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='fee_note_terms',
            field=models.TextField(blank=True, default='', help_text='Free-form notice appended below every fee note (instalment terms, bank account details, reminders). Rendered as plain text with line breaks preserved.'),
        ),
    ]
