# Generated by Django 5.2.15 on 2026-09-06 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_role_rolepermission_userroleassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportroute',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_provider',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='roadworthiness_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_vehicles', to='core.transportroute'),
        ),
        migrations.CreateModel(
            name='TransportStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_type', models.CharField(choices=[('driver', 'Driver'), ('attendant', 'Attendant')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('alt_phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('national_id', models.CharField(blank=True, default='', max_length=50)),
                ('license_number', models.CharField(blank=True, default='', max_length=50)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_staff_roles', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='transportroute',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendant_routes', to='core.transportstaff'),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_routes', to='core.transportstaff'),
        ),
        migrations.CreateModel(
            name='TransportStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('landmark', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('dropoff_time', models.TimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='core.transportroute')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='core.transportstop')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransportAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('both', 'Pickup & Drop-off'), ('pickup', 'Pickup only'), ('dropoff', 'Drop-off only')], default='both', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('finance_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_assignments', to='core.financefee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='core.transportroute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('boarding_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='core.transportroutestop')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_studen_tenant__417787_idx'), models.Index(fields=['student'], name='core_studen_student_5e51c8_idx'), models.Index(fields=['route'], name='core_studen_route_i_b50d8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTransportAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('both', 'Pickup & Drop-off'), ('pickup', 'Pickup only'), ('dropoff', 'Drop-off only')], default='both', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='core.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='core.transportroute')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('boarding_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_assignments', to='core.transportroutestop')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_employ_tenant__bf8d2f_idx'), models.Index(fields=['employee'], name='core_employ_employe_298dc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransportSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_pickup_time', models.TimeField(blank=True, null=True)),
                ('default_dropoff_time', models.TimeField(blank=True, null=True)),
                ('billing_frequency', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('termly', 'Termly'), ('yearly', 'Yearly')], default='termly', max_length=20)),
                ('attendance_tracking_enabled', models.BooleanField(default=False)),
                ('notify_on_changes', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_settings', to='core.academicyear')),
                ('fee_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_settings', to='core.feecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='core_transp_tenant__3ae3ea_idx')],
                'unique_together': {('tenant', 'academic_year')},
            },
        ),
        migrations.AddIndex(
            model_name='transportstaff',
            index=models.Index(fields=['tenant'], name='core_transp_tenant__4836b5_idx'),
        ),
        migrations.AddIndex(
            model_name='transportstaff',
            index=models.Index(fields=['staff_type'], name='core_transp_staff_t_0c5365_idx'),
        ),
        migrations.AddIndex(
            model_name='transportstop',
            index=models.Index(fields=['tenant'], name='core_transp_tenant__f0114e_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroutestop',
            index=models.Index(fields=['tenant'], name='core_transp_tenant__1e7ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroutestop',
            index=models.Index(fields=['route', 'order'], name='core_transp_route_i_4cdf11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transportroutestop',
            unique_together={('route', 'stop')},
        ),
    ]
