# Generated by Django 5.2.15 on 2026-09-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_feecollectionparticular'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feecollectionparticular',
            new_name='core_feecol_tenant__83a486_idx',
            old_name='core_feecp_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='feecollectionparticular',
            new_name='core_feecol_fee_col_38eda1_idx',
            old_name='core_feecp_fc_idx',
        ),
    ]
