# Generated by Django 5.2.15 on 2026-09-07 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_alter_payment_method_add_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfield',
            name='applies_to',
            field=models.CharField(choices=[('employee', 'Employee record'), ('student', 'Student record'), ('admission', 'Admission application')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='additionalfield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='additionalfield',
            name='options',
            field=models.TextField(blank=True, help_text='Newline-separated choices for select/radio inputs'),
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False, help_text='Flagged as expected for every student')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('fee_due', 'Fee due / reminder'), ('fee_payment_received', 'Fee payment received'), ('attendance_absent', 'Student marked absent'), ('exam_results_published', 'Exam results published'), ('report_card_published', 'Report card published'), ('announcement', 'General announcement'), ('admission_status_change', 'Admission status change'), ('assignment_posted', 'Assignment posted')], max_length=50)),
                ('audience', models.CharField(choices=[('guardians', 'Guardians'), ('students', 'Students'), ('staff', 'Staff'), ('admins', 'Administrators')], default='guardians', max_length=20)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=True)),
                ('send_in_app', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['event', 'audience'],
            },
        ),
        migrations.CreateModel(
            name='PortalFeatureAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('attendance', 'Attendance'), ('results', 'Results / report cards'), ('invoices', 'Invoices'), ('fees', 'Fee payments'), ('assignments', 'Assignments'), ('transport', 'Transport'), ('announcements', 'Announcements'), ('documents', 'Student documents'), ('timetable', 'Timetable')], max_length=40)),
                ('is_enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_by_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.documentcategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentExemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exemption_type', models.CharField(choices=[('report_block', 'Report-card blocking (fees etc.)'), ('ranking', 'Class ranking / position'), ('grading', 'Grading & report-card calculations'), ('promotion', 'Automatic promotion')], max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Leave blank for an open-ended exemption', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exemptions', to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='core.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminologyOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=60)),
                ('replacement', models.CharField(max_length=60)),
                ('replacement_plural', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionAdditionalDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_details', to='core.extendedadmissionapplication')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_values', to='core.additionalfield')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'application'], name='core_admiss_tenant__8ccdad_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'field'), name='uniq_admissionadditionaldetail_app_field')],
            },
        ),
        migrations.CreateModel(
            name='ClientApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('other', 'Other')], default='android', max_length=20)),
                ('min_supported_version', models.CharField(blank=True, max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_enabled'], name='core_client_tenant__17ff1e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_clientapp_tenant_slug')],
            },
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='core_docume_tenant__fe5c2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_documentcategory_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['tenant', 'event', 'is_active'], name='core_notifi_tenant__abcc08_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'event', 'audience'), name='uniq_notificationrule_tenant_event_audience'),
        ),
        migrations.AddIndex(
            model_name='portalfeatureaccess',
            index=models.Index(fields=['tenant'], name='core_portal_tenant__667194_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalfeatureaccess',
            constraint=models.UniqueConstraint(fields=('tenant', 'feature'), name='uniq_portalfeature_tenant_feature'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['tenant', 'student'], name='core_studen_tenant__1298b9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexemption',
            index=models.Index(fields=['tenant', 'exemption_type', 'is_active'], name='core_studen_tenant__d6c747_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentexemption',
            constraint=models.UniqueConstraint(fields=('tenant', 'student', 'exemption_type', 'academic_year'), name='uniq_studentexemption_scope'),
        ),
        migrations.AddIndex(
            model_name='terminologyoverride',
            index=models.Index(fields=['tenant', 'is_active'], name='core_termin_tenant__eb735c_idx'),
        ),
        migrations.AddConstraint(
            model_name='terminologyoverride',
            constraint=models.UniqueConstraint(fields=('tenant', 'term'), name='uniq_terminology_tenant_term'),
        ),
    ]
