# Generated by Django 5.2.15 on 2026-09-08 10:26

import core.db_fields
from django.db import migrations


def encrypt_existing(apps, schema_editor):
    """Re-save every QuickBooksIntegration row so its client_secret / tokens
    are written back through EncryptedTextField.get_prep_value (i.e. encrypted).
    Runs once per tenant schema under migrate_schemas.
    """
    Integration = apps.get_model("core", "QuickBooksIntegration")
    for row in Integration.objects.all().iterator():
        Integration.objects.filter(pk=row.pk).update(
            client_secret=row.client_secret,
            access_token=row.access_token,
            refresh_token=row.refresh_token,
        )


def decrypt_existing(apps, schema_editor):
    """Best-effort reverse: write the decrypted plaintext straight to the
    columns with raw SQL so it is not re-encrypted on the way out.
    """
    from core.db_fields import decrypt_str

    Integration = apps.get_model("core", "QuickBooksIntegration")
    table = Integration._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT id, client_secret, access_token, refresh_token FROM {table}"
        )
        rows = cursor.fetchall()
        for pk, secret, access, refresh in rows:
            cursor.execute(
                f"UPDATE {table} SET client_secret = %s, access_token = %s, "
                f"refresh_token = %s WHERE id = %s",
                [
                    decrypt_str(secret) if secret is not None else None,
                    decrypt_str(access) if access is not None else None,
                    decrypt_str(refresh) if refresh is not None else None,
                    pk,
                ],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_additionalfield_applies_to_additionalfield_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbooksintegration',
            name='access_token',
            field=core.db_fields.EncryptedTextField(blank=True, help_text='Current access token (encrypted at rest)', null=True),
        ),
        migrations.AlterField(
            model_name='quickbooksintegration',
            name='client_secret',
            field=core.db_fields.EncryptedTextField(help_text='QuickBooks App Client Secret (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='quickbooksintegration',
            name='refresh_token',
            field=core.db_fields.EncryptedTextField(blank=True, help_text='Refresh token (encrypted at rest)', null=True),
        ),
        migrations.RunPython(encrypt_existing, decrypt_existing),
    ]
