# Generated by Django 5.2.15 on 2026-09-08 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_employment_status(apps, schema_editor):
    """Existing inactive employees are treated as 'exited'; active ones keep
    the 'active' default."""
    Employee = apps.get_model("core", "Employee")
    Employee.objects.filter(status=False).update(employment_status="exited")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_encrypt_quickbooks_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('notice_period', 'Notice Period'), ('exited', 'Exited')], db_index=True, default='active', help_text='HR-managed lifecycle status. Independent of the boolean `status` flag, which stays the login/soft-delete gate.', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, help_text='NRC / passport number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_relation',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo shown in the HR portal.', null=True, upload_to='employee_photos/'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='document',
            field=models.FileField(blank=True, help_text='Supporting document (e.g. medical certificate).', null=True, upload_to='employee_leave_documents/'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_acted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_leaves', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='hr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='supervisor_acted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='supervisor_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_leaves', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='supervisor_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='supervisor_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave'), ('half_day', 'Half Day'), ('official_duty', 'Official Duty'), ('training', 'Training'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('uploaded_by_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_documents', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualification_type', models.CharField(choices=[('academic', 'Academic'), ('teaching', 'Teaching'), ('professional', 'Professional'), ('other', 'Other')], default='academic', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('year_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('is_highest', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifications', to='core.employeedocument')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications_detail', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-is_highest', '-year_obtained'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('employed', 'Employed'), ('promotion', 'Promotion'), ('department_change', 'Department Change'), ('position_change', 'Position Change'), ('grade_change', 'Grade Change'), ('manager_change', 'Reporting Manager Change'), ('salary_change', 'Salary Change'), ('contract_renewal', 'Contract Renewal'), ('status_change', 'Status Change'), ('exit', 'Exit')], max_length=30)),
                ('effective_date', models.DateField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_label', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('contract', 'Contract'), ('probation', 'Probation'), ('document', 'Document'), ('training', 'Training'), ('appraisal', 'Appraisal'), ('onboarding', 'Onboarding'), ('exit', 'Exit'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('assigned_to_id', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=10)),
                ('dedupe_key', models.CharField(blank=True, help_text='Set on auto-generated tasks to prevent duplicates.', max_length=200)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_tasks', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('probation', 'Probation'), ('temporary', 'Temporary'), ('casual', 'Casual'), ('consultant', 'Consultant / Contract'), ('intern', 'Internship')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Blank = open-ended', null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('salary_review_date', models.DateField(blank=True, null=True)),
                ('renewal_status', models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('renewal_pending', 'Renewal Pending'), ('renewed', 'Renewed'), ('not_renewed', 'Not Renewed'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='employee_contracts/')),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.employee')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_by', to='core.employeecontract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='core_employ_tenant__dc0801_idx'), models.Index(fields=['tenant', 'renewal_status'], name='core_employ_tenant__197f10_idx'), models.Index(fields=['tenant', 'end_date'], name='core_employ_tenant__e09597_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['tenant', 'employee'], name='core_employ_tenant__fab34c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['tenant', 'expiry_date'], name='core_employ_tenant__071523_idx'),
        ),
        migrations.AddIndex(
            model_name='employeequalification',
            index=models.Index(fields=['tenant', 'employee'], name='core_employ_tenant__9ca8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistoryevent',
            index=models.Index(fields=['tenant', 'employee'], name='core_employ_tenant__f193e4_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistoryevent',
            index=models.Index(fields=['tenant', 'event_type'], name='core_employ_tenant__6a0455_idx'),
        ),
        migrations.AddIndex(
            model_name='hrauditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='core_hraudi_tenant__be0ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='hrauditlog',
            index=models.Index(fields=['tenant', 'target_type', 'target_id'], name='core_hraudi_tenant__66e708_idx'),
        ),
        migrations.AddIndex(
            model_name='hrtask',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='core_hrtask_tenant__33166f_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrtask',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__gt', '')), fields=('tenant', 'dedupe_key'), name='uniq_hrtask_tenant_dedupe'),
        ),
        migrations.RunPython(backfill_employment_status, migrations.RunPython.noop),
    ]
