# Generated by Django 5.2.15 on 2026-09-08 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_employee_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('number_of_positions', models.PositiveIntegerField(default=1)),
                ('job_description', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Internship')], default='full_time', max_length=20)),
                ('is_teaching_role', models.BooleanField(default=False)),
                ('date_advertised', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='core.employeedepartment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='applicant_cvs/')),
                ('qualifications_summary', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('reference_check', 'Reference Check'), ('offered', 'Offered'), ('hired', 'Hired'), ('unsuccessful', 'Unsuccessful')], db_index=True, default='applied', max_length=20)),
                ('stage_changed_at', models.DateTimeField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_panel', models.CharField(blank=True, max_length=500)),
                ('interview_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interview_comments', models.TextField(blank=True)),
                ('reference_check_notes', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('converted_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_applicant', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='core.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['tenant', 'status'], name='core_vacanc_tenant__80a037_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['tenant', 'vacancy'], name='core_applic_tenant__2055a9_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['tenant', 'stage'], name='core_applic_tenant__e40ced_idx'),
        ),
    ]
