# Generated by Django 5.2.15 on 2026-09-08 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_onboardingchecklist_onboardingitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_period', models.CharField(max_length=100)),
                ('review_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('employee_ack', 'Awaiting Employee'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('is_teacher_review', models.BooleanField(default=False)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvement_areas', models.TextField(blank=True)),
                ('development_actions', models.TextField(blank=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('observation_document', models.FileField(blank=True, null=True, upload_to='performance_observations/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='core.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='core.performancereview')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['tenant', 'employee'], name='core_perfor_tenant__142641_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['tenant', 'status'], name='core_perfor_tenant__7fff09_idx'),
        ),
        migrations.AddIndex(
            model_name='performancecriterion',
            index=models.Index(fields=['tenant', 'review'], name='core_perfor_tenant__461ea1_idx'),
        ),
    ]
