# Generated by Django 5.2.15 on 2026-09-08 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_performancereview_performancecriterion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('child_safeguarding', 'Child Safeguarding'), ('first_aid', 'First Aid'), ('fire_safety', 'Fire / Safety'), ('curriculum', 'Curriculum Training'), ('classroom_management', 'Classroom Management'), ('ict', 'ICT'), ('leadership', 'Leadership'), ('professional_development', 'Professional Development'), ('other', 'Other')], default='other', max_length=30)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training_certificates/')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-training_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='core_traini_tenant__f56b22_idx'), models.Index(fields=['tenant', 'category'], name='core_traini_tenant__6a874e_idx'), models.Index(fields=['tenant', 'expiry_date'], name='core_traini_tenant__c39d3c_idx')],
            },
        ),
    ]
