# Generated by Django 5.2.15 on 2026-09-08 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_trainingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exit_type', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('end_of_contract', 'End of Contract'), ('redundancy', 'Redundancy'), ('death', 'Death in Service'), ('other', 'Other')], max_length=20)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('exit_interview_notes', models.TextField(blank=True)),
                ('final_payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('outstanding_leave_days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('handover_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_record', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitClearanceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('done_by_id', models.UUIDField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_items', to='core.employeeexit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='employeeexit',
            index=models.Index(fields=['tenant', 'status'], name='core_employ_tenant__408f72_idx'),
        ),
        migrations.AddIndex(
            model_name='exitclearanceitem',
            index=models.Index(fields=['tenant', 'exit'], name='core_exitcl_tenant__3deb4e_idx'),
        ),
    ]
