# Generated by Django 5.2.15 on 2026-09-08 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_employeeexit_exitclearanceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('misconduct', 'Misconduct'), ('poor_performance', 'Poor Performance'), ('attendance', 'Attendance / Punctuality'), ('policy_breach', 'Policy Breach'), ('insubordination', 'Insubordination'), ('safeguarding', 'Safeguarding Concern'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('gross', 'Gross Misconduct')], default='minor', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('reported_by_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('hearing', 'Hearing Scheduled'), ('action_taken', 'Action Taken'), ('appealed', 'Appealed'), ('closed', 'Closed')], db_index=True, default='open', max_length=30)),
                ('investigation_notes', models.TextField(blank=True)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('none', 'No Outcome Yet'), ('no_action', 'No Action / Cleared'), ('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('final_warning', 'Final Written Warning'), ('suspension', 'Suspension'), ('demotion', 'Demotion'), ('dismissal', 'Dismissal')], default='none', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('warning_expiry_date', models.DateField(blank=True, null=True)),
                ('appeal_notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='hr_disciplinary/')),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_cases', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='core_discip_tenant__25a809_idx'), models.Index(fields=['tenant', 'employee'], name='core_discip_tenant__8dd54b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('harassment', 'Harassment / Bullying'), ('discrimination', 'Discrimination'), ('workload', 'Workload / Working Hours'), ('pay', 'Pay / Benefits'), ('management', 'Management / Supervision'), ('working_conditions', 'Working Conditions'), ('safeguarding', 'Safeguarding Concern'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('mediation', 'Mediation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], db_index=True, default='submitted', max_length=20)),
                ('handled_by_id', models.UUIDField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='hr_grievance/')),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('against', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances_against', to='core.employee')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances_raised', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='core_grieva_tenant__fa1dd2_idx'), models.Index(fields=['tenant', 'raised_by'], name='core_grieva_tenant__8c44a4_idx')],
            },
        ),
    ]
