# Generated by Django 5.2.15 on 2026-09-08 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_disciplinarycase_grievance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('safeguarding', 'Safeguarding / Child Protection'), ('code_of_conduct', 'Code of Conduct'), ('hr', 'HR / Employment'), ('health_safety', 'Health & Safety'), ('it', 'IT / Acceptable Use'), ('finance', 'Finance / Procurement'), ('other', 'Other')], default='hr', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='hr_policies/')),
                ('version', models.CharField(blank=True, max_length=40)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('requires_acknowledgement', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
            ],
            options={
                'ordering': ['-effective_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='core.policydocument')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policydocument',
            index=models.Index(fields=['tenant', 'is_active'], name='core_policy_tenant__01d5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='policydocument',
            index=models.Index(fields=['tenant', 'category'], name='core_policy_tenant__0f5c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgement',
            index=models.Index(fields=['tenant', 'employee'], name='core_policy_tenant__860c44_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyacknowledgement',
            constraint=models.UniqueConstraint(fields=('tenant', 'policy', 'employee'), name='uniq_policyack_tenant_policy_employee'),
        ),
    ]
