# Generated by Django 5.2.15 on 2026-09-11 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_schoolmodule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schoolmodule',
            name='unique_school_module',
        ),
        migrations.RenameIndex(
            model_name='schoolmodule',
            new_name='core_school_school__2e356d_idx',
            old_name='core_schoolm_school_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolmodule',
            new_name='core_school_module_493bd6_idx',
            old_name='core_schoolm_module_idx',
        ),
        migrations.AlterUniqueTogether(
            name='schoolmodule',
            unique_together={('school', 'module')},
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='footer_quote',
            field=models.TextField(blank=True, default='', help_text='Optional quote or motto to appear on report cards'),
        ),
        migrations.AlterField(
            model_name='school',
            name='footer_quote',
            field=models.TextField(blank=True, default='', help_text='Optional quote or motto to appear on report cards'),
        ),
        migrations.AlterField(
            model_name='schoolmodule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='schoolmodule',
            name='tenant',
        ),
    ]
