# Generated by Django 5.2.15 on 2026-09-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_remove_schoolmodule_unique_school_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodule',
            name='module',
            field=models.CharField(choices=[('academics', 'Academics'), ('admissions', 'Admissions'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('hostel', 'Hostel'), ('transport', 'Transport'), ('library', 'Library'), ('parent_portal', 'Parent Portal')], help_text="Module key (e.g. 'finance', 'hr', 'hostel') — must match core.modules.MODULES", max_length=50),
        ),
    ]
