# Generated by Django 5.2.15 on 2026-09-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_demo_request_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='demorequest',
            new_name='core_demore_email_95c29b_idx',
            old_name='core_demorea_email_idx',
        ),
        migrations.RenameIndex(
            model_name='demorequest',
            new_name='core_demore_status_26d5fc_idx',
            old_name='core_demorea_status_idx',
        ),
        migrations.RenameIndex(
            model_name='demorequest',
            new_name='core_demore_created_8bfbe3_idx',
            old_name='core_demorea_created_at_idx',
        ),
        migrations.AlterField(
            model_name='school',
            name='admission_enabled',
            field=models.BooleanField(default=False, help_text='Whether the admission portal is enabled for this school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Feature flags {parent_portal, teacher_portal, librarian_portal, hr_portal, admission_portal}'),
        ),
        migrations.AlterField(
            model_name='school',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media links {twitter, facebook, instagram, linkedin}'),
        ),
    ]
