# Generated by Django 5.2.15 on 2026-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_disable_non_required_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='billing_notes',
            field=models.TextField(blank=True, default='', help_text='Free-form notes for the platform operator (invoice references, payment dates, follow-ups). Not shown to the school.'),
        ),
        migrations.AddField(
            model_name='school',
            name='billing_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended')], default='trial', help_text='Manually maintained by the platform operator. Trial/active grant access; past_due/suspended block the staff dashboard and portal.', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='plan_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', help_text='Pricing tier this school is contracted for.', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text="When the trial period ends. Ignored unless billing_status is 'trial'.", null=True),
        ),
    ]
