# Generated by Django 5.2.15 on 2026-09-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_school_billing_notes_school_billing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='converted_school',
            field=models.ForeignKey(blank=True, help_text='The tenant provisioned from this request, once converted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_requests', to='core.school'),
        ),
    ]
