"""HR task / reminder desk.

Manual tasks are plain CRUD. Auto tasks are (re)generated by
:meth:`HRTaskService.generate_from_rules` — each carries a ``dedupe_key`` so a
nightly run never creates the same reminder twice.
"""
from __future__ import annotations

from datetime import date, timedelta
from typing import Any, Optional

from django.utils import timezone

from core.models import (
    DisciplinaryCase, Employee, EmployeeContract, EmployeeDocument, HRTask,
    PerformanceReview, TrainingRecord,
)
from .base import TenantAwareService
from .exceptions import NotFoundException, ValidationException
from .hr_audit import record_hr_audit
from .logging_service import ServiceLogger, logged_operation

CONTRACT_WINDOWS = (90, 60, 30)
DOCUMENT_WINDOW = 30
PROBATION_WINDOW = 14
TRAINING_WINDOW = 60
APPRAISAL_WINDOW = 30
WARNING_WINDOW = 14


class HRTaskService(TenantAwareService[HRTask]):
    def __init__(self, tenant):
        super().__init__(HRTask, tenant)
        self.logger = ServiceLogger("hr_task", tenant)

    # ── reads ────────────────────────────────────────────────────────────
    def list_tasks(self, *, status: str = None, category: str = None, employee_id: Any = None):
        qs = self.get_base_queryset().select_related("employee")
        if status:
            qs = qs.filter(status=status)
        if category:
            qs = qs.filter(category=category)
        if employee_id:
            qs = qs.filter(employee_id=employee_id)
        return qs

    def open_count(self) -> int:
        return self.count(status="pending") + self.count(status="in_progress")

    # ── writes ───────────────────────────────────────────────────────────
    @logged_operation(action="create", resource_type="hr_task", log_result=True)
    def create_task(
        self,
        *,
        title: str,
        description: str = "",
        category: str = "general",
        due_date: date = None,
        employee_id: Any = None,
        assigned_to_id: Any = None,
        actor=None,
    ) -> HRTask:
        if not title.strip():
            raise ValidationException("A task title is required.")
        task = self.create(
            title=title.strip(),
            description=description or "",
            category=category,
            due_date=due_date,
            employee_id=employee_id,
            assigned_to_id=assigned_to_id,
            source=HRTask.SOURCE_MANUAL,
            created_by_id=getattr(actor, "id", None),
        )
        record_hr_audit(
            self.tenant, actor=actor, action="task.create",
            target_type="hr_task", target_id=task.id, new_value=title,
        )
        return task

    @logged_operation(action="update", resource_type="hr_task")
    def update_task(self, task_id: Any, actor=None, **fields) -> HRTask:
        task = self.get_by_id(task_id)
        allowed = {"title", "description", "category", "due_date", "status", "assigned_to_id"}
        touched = {k: v for k, v in fields.items() if k in allowed}
        old_status = task.status
        for key, value in touched.items():
            setattr(task, key, value)
        if "status" in touched and touched["status"] == "completed" and not task.completed_at:
            task.completed_at = timezone.now()
        task.save()
        if "status" in touched and touched["status"] != old_status:
            record_hr_audit(
                self.tenant, actor=actor, action="task.status",
                target_type="hr_task", target_id=task_id,
                field="status", old_value=old_status, new_value=task.status,
            )
        return task

    # ── auto-generation ────────────────────────────────────────────────
    def generate_from_rules(self, *, today: date = None) -> int:
        """Create auto tasks for contract expiry, probation end and document
        expiry. Idempotent via ``dedupe_key``. Returns the number created."""
        today = today or date.today()
        created = 0
        created += self._contracts(today)
        created += self._probation(today)
        created += self._documents(today)
        created += self._training(today)
        created += self._appraisals(today)
        created += self._warnings(today)
        return created

    def _ensure(self, *, dedupe_key: str, **defaults) -> bool:
        _, was_created = HRTask.objects.get_or_create(
            tenant=self.tenant,
            dedupe_key=dedupe_key,
            defaults={**defaults, "source": HRTask.SOURCE_AUTO},
        )
        return was_created

    def _contracts(self, today: date) -> int:
        made = 0
        horizon = today + timedelta(days=CONTRACT_WINDOWS[0])
        qs = EmployeeContract.objects.filter(
            tenant=self.tenant, end_date__isnull=False,
            end_date__gte=today, end_date__lte=horizon,
        ).select_related("employee").exclude(renewal_status__in=["renewed", "not_renewed"])
        for c in qs:
            days = (c.end_date - today).days
            window = next((w for w in CONTRACT_WINDOWS if days <= w), CONTRACT_WINDOWS[0])
            key = f"contract:{c.id}:{window}"
            if self._ensure(
                dedupe_key=key,
                title=f"Contract expires in {days} days — {c.employee.full_name}",
                description=f"{c.employee.full_name}'s {c.get_contract_type_display()} "
                            f"contract ends {c.end_date:%d %b %Y}.",
                category="contract", due_date=c.end_date, employee=c.employee,
            ):
                made += 1
        return made

    def _probation(self, today: date) -> int:
        made = 0
        horizon = today + timedelta(days=PROBATION_WINDOW)
        qs = EmployeeContract.objects.filter(
            tenant=self.tenant, probation_end_date__isnull=False,
            probation_end_date__gte=today, probation_end_date__lte=horizon,
        ).select_related("employee")
        for c in qs:
            key = f"probation:{c.id}"
            if self._ensure(
                dedupe_key=key,
                title=f"Probation review due — {c.employee.full_name}",
                description=f"Probation ends {c.probation_end_date:%d %b %Y}.",
                category="probation", due_date=c.probation_end_date, employee=c.employee,
            ):
                made += 1
        return made

    def _training(self, today: date) -> int:
        """Mandatory / certified training coming up for renewal."""
        made = 0
        horizon = today + timedelta(days=TRAINING_WINDOW)
        qs = TrainingRecord.objects.filter(
            tenant=self.tenant, expiry_date__isnull=False,
            expiry_date__gte=today, expiry_date__lte=horizon,
            employee__status=True,
        ).select_related("employee")
        for t in qs:
            key = f"training:{t.id}"
            if self._ensure(
                dedupe_key=key,
                title=f"Training renewal due — {t.name} ({t.employee.full_name})",
                description=f"{t.name} expires {t.expiry_date:%d %b %Y}.",
                category="training", due_date=t.expiry_date, employee=t.employee,
            ):
                made += 1
        return made

    def _appraisals(self, today: date) -> int:
        """Performance reviews whose ``next_review_date`` is approaching and
        which have no open successor review."""
        made = 0
        horizon = today + timedelta(days=APPRAISAL_WINDOW)
        qs = PerformanceReview.objects.filter(
            tenant=self.tenant, next_review_date__isnull=False,
            next_review_date__lte=horizon, status="completed",
            employee__status=True,
        ).select_related("employee")
        for r in qs:
            key = f"appraisal:{r.employee_id}:{r.next_review_date:%Y-%m}"
            if self._ensure(
                dedupe_key=key,
                title=f"Appraisal due — {r.employee.full_name}",
                description=f"Next review was scheduled for {r.next_review_date:%d %b %Y}.",
                category="appraisal", due_date=r.next_review_date, employee=r.employee,
            ):
                made += 1
        return made

    def _warnings(self, today: date) -> int:
        """Disciplinary warnings reaching their expiry — HR should confirm the
        warning lapses or is escalated."""
        made = 0
        horizon = today + timedelta(days=WARNING_WINDOW)
        qs = DisciplinaryCase.objects.filter(
            tenant=self.tenant, warning_expiry_date__isnull=False,
            warning_expiry_date__gte=today, warning_expiry_date__lte=horizon,
        ).exclude(status="closed").select_related("employee")
        for c in qs:
            key = f"warning:{c.id}"
            if self._ensure(
                dedupe_key=key,
                title=f"Warning expires — {c.employee.full_name}",
                description=f"'{c.title}' warning lapses {c.warning_expiry_date:%d %b %Y}.",
                category="general", due_date=c.warning_expiry_date, employee=c.employee,
            ):
                made += 1
        return made

    def _documents(self, today: date) -> int:
        made = 0
        horizon = today + timedelta(days=DOCUMENT_WINDOW)
        qs = EmployeeDocument.objects.filter(
            tenant=self.tenant, expiry_date__isnull=False,
            expiry_date__gte=today, expiry_date__lte=horizon,
        ).select_related("employee")
        for d in qs:
            key = f"document:{d.id}"
            if self._ensure(
                dedupe_key=key,
                title=f"Document expiring — {d.document_type} ({d.employee.full_name})",
                description=f"{d.document_type} expires {d.expiry_date:%d %b %Y}.",
                category="document", due_date=d.expiry_date, employee=d.employee,
            ):
                made += 1
        return made
