/**
 * Invoices list page.
 *
 * FamilyInvoice is a guardian-level consolidated invoice for an academic
 * year, entirely system-generated by InvoiceService — there is no create,
 * edit, or mark-paid action here, only viewing.
 *
 * Uses design system components:
 * - Page wrapper for consistent layout
 * - PageHeader for title
 * - DataTable with StatusBadge for invoice status display
 */

'use client';

export const dynamic = 'force-dynamic';

import Link from 'next/link';
import { Alert, IconButton } from '@mui/material';
import { Visibility as ViewIcon } from '@mui/icons-material';
import type { GridColDef } from '@mui/x-data-grid';
import { useTenantStore } from '@/lib/tenant/store';
import { useInvoiceList, Invoice } from '@/features/finance/hooks';
import { useServerTable } from '@/hooks/useServerTable';
import { DataTable } from '@/components/data-table/DataTable';
import { Page } from '@/components/page/Page';
import { PageHeader } from '@/components/page/PageHeader';
import { PageContent } from '@/components/page/PageContent';
import { StatusBadge } from '@/components/data/StatusBadge';

export default function InvoicesPage() {
  const { can, isModuleEnabled } = useTenantStore();

  const table = useServerTable({ initialOrdering: '-generated_at' });
  const { data, isLoading, error, refetch } = useInvoiceList(table.queryParams);

  const columns: GridColDef<Invoice>[] = [
    { field: 'invoice_number', headerName: 'Invoice #', flex: 1, minWidth: 140 },
    { field: 'guardian_name', headerName: 'Guardian', flex: 1.5, minWidth: 170 },
    { field: 'academic_year_label', headerName: 'Academic Year', flex: 1, minWidth: 130 },
    {
      field: 'status',
      headerName: 'Status',
      flex: 0.8,
      minWidth: 100,
      sortable: true,
      renderCell: (params) => {
        const status = params.row.status?.toLowerCase() ?? 'default';
        return <StatusBadge status={status as any} />;
      },
    },
    {
      field: 'subtotal',
      headerName: 'Subtotal',
      flex: 0.8,
      minWidth: 110,
      valueGetter: (params) => `$${Number(params.row.subtotal).toFixed(2)}`,
    },
    {
      field: 'balance_due',
      headerName: 'Balance Due',
      flex: 0.8,
      minWidth: 120,
      valueGetter: (params) => `$${Number(params.row.balance_due).toFixed(2)}`,
    },
    { field: 'due_date', headerName: 'Due Date', flex: 0.8, minWidth: 120 },
    {
      field: 'actions',
      headerName: 'Actions',
      flex: 0.5,
      minWidth: 80,
      sortable: false,
      filterable: false,
      align: 'right',
      headerAlign: 'right',
      renderCell: (params) => (
        <Link href={`/dashboard/invoices/${params.row.id}`} passHref legacyBehavior>
          <IconButton size="small" component="a" title="View">
            <ViewIcon fontSize="small" />
          </IconButton>
        </Link>
      ),
    },
  ];

  return (
    <Page>
      <PageHeader
        title="Invoices"
        description="View and manage student/family invoices"
      />

      <PageContent>
        {!isModuleEnabled('finance') ? (
          <Alert severity="info">
            The Finance module is not enabled. Contact your administrator.
          </Alert>
        ) : !can('finance.invoices.view') ? (
          <Alert severity="error">
            You do not have permission to view invoices.
          </Alert>
        ) : (
          <DataTable<Invoice>
            rows={data?.results || []}
            columns={columns}
            rowCount={data?.count || 0}
            loading={isLoading}
            error={error as Error | null}
            onRetry={() => refetch()}
            paginationModel={table.paginationModel}
            onPaginationModelChange={table.onPaginationModelChange}
            onSortModelChange={(model) =>
              table.onSortModelChange(model.map((m) => ({ field: m.field, sort: m.sort ?? null })))
            }
            search={table.search}
            onSearchChange={table.onSearchChange}
            searchPlaceholder="Search by guardian name or invoice number"
            emptyMessage="No invoices found"
          />
        )}
      </PageContent>
    </Page>
  );
}
