/**
 * Invoices list page.
 *
 * FamilyInvoice is a guardian-level consolidated invoice for an academic
 * year, entirely system-generated by InvoiceService — there is no create,
 * edit, or mark-paid action here, only viewing.
 */

'use client';

export const dynamic = 'force-dynamic';

import Link from 'next/link';
import { Container, Box, Typography, Alert, Chip, IconButton } from '@mui/material';
import { Visibility as ViewIcon } from '@mui/icons-material';
import type { GridColDef } from '@mui/x-data-grid';
import { useTenantStore } from '@/lib/tenant/store';
import { useInvoiceList, Invoice } from '@/features/finance/hooks';
import { useServerTable } from '@/hooks/useServerTable';
import { DataTable } from '@/components/data-table/DataTable';

const statusColors: Record<string, 'default' | 'primary' | 'secondary' | 'error' | 'info' | 'success' | 'warning'> = {
  open: 'info',
  paid: 'success',
  void: 'default',
};

export default function InvoicesPage() {
  const { can, isModuleEnabled } = useTenantStore();

  const table = useServerTable({ initialOrdering: '-generated_at' });
  const { data, isLoading, error, refetch } = useInvoiceList(table.queryParams);

  if (!isModuleEnabled('finance')) {
    return (
      <Container maxWidth="lg">
        <Box sx={{ py: 4 }}>
          <Alert severity="info">
            The Finance module is not enabled. Contact your administrator.
          </Alert>
        </Box>
      </Container>
    );
  }

  if (!can('finance.invoices.view')) {
    return (
      <Container maxWidth="lg">
        <Box sx={{ py: 4 }}>
          <Alert severity="error">
            You do not have permission to view invoices.
          </Alert>
        </Box>
      </Container>
    );
  }

  const columns: GridColDef<Invoice>[] = [
    { field: 'invoice_number', headerName: 'Invoice #', flex: 1, minWidth: 140 },
    { field: 'guardian_name', headerName: 'Guardian', flex: 1.5, minWidth: 170 },
    { field: 'academic_year_label', headerName: 'Academic Year', flex: 1, minWidth: 130 },
    {
      field: 'status',
      headerName: 'Status',
      flex: 0.8,
      minWidth: 100,
      sortable: true,
      renderCell: (params) => (
        <Chip label={params.row.status} color={statusColors[params.row.status]} size="small" />
      ),
    },
    {
      field: 'subtotal',
      headerName: 'Subtotal',
      flex: 0.8,
      minWidth: 110,
      valueGetter: (params) => `$${Number(params.row.subtotal).toFixed(2)}`,
    },
    {
      field: 'balance_due',
      headerName: 'Balance Due',
      flex: 0.8,
      minWidth: 120,
      valueGetter: (params) => `$${Number(params.row.balance_due).toFixed(2)}`,
    },
    { field: 'due_date', headerName: 'Due Date', flex: 0.8, minWidth: 120 },
    {
      field: 'actions',
      headerName: 'Actions',
      flex: 0.5,
      minWidth: 80,
      sortable: false,
      filterable: false,
      align: 'right',
      headerAlign: 'right',
      renderCell: (params) => (
        <Link href={`/dashboard/invoices/${params.row.id}`} passHref legacyBehavior>
          <IconButton size="small" component="a" title="View">
            <ViewIcon fontSize="small" />
          </IconButton>
        </Link>
      ),
    },
  ];

  return (
    <Container maxWidth="lg">
      <Box sx={{ py: 4 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
          <Typography variant="h4" component="h1">
            Invoices
          </Typography>
        </Box>

        <DataTable<Invoice>
          rows={data?.results || []}
          columns={columns}
          rowCount={data?.count || 0}
          loading={isLoading}
          error={error as Error | null}
          onRetry={() => refetch()}
          paginationModel={table.paginationModel}
          onPaginationModelChange={table.onPaginationModelChange}
          onSortModelChange={(model) =>
            table.onSortModelChange(model.map((m) => ({ field: m.field, sort: m.sort ?? null })))
          }
          search={table.search}
          onSearchChange={table.onSearchChange}
          searchPlaceholder="Search by guardian name or invoice number"
          emptyMessage="No invoices found"
        />
      </Box>
    </Container>
  );
}
