"""Portal API routes, mounted at /api/portal/."""
from django.urls import path

from . import (
    hr_exit, hr_onboarding, hr_performance, hr_policies, hr_recruitment,
    hr_relations, hr_reports, hr_settings_views, hr_training, hr_views,
    payroll_views, views,
)

app_name = "portal"

urlpatterns = [
    # Auth
    path("auth/login/", views.PortalTokenObtainView.as_view(), name="login"),
    path("auth/refresh/", views.PortalTokenRefreshView.as_view(), name="refresh"),
    path("auth/me/", views.MeView.as_view(), name="me"),
    path("auth/password-reset/request/", views.PasswordResetRequestView.as_view(), name="password-reset-request"),
    path("auth/password-reset/confirm/", views.PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("auth/password-change-first-time/", views.FirstTimePasswordChangeView.as_view(), name="password-change-first-time"),
    path("auth/password-change/", views.ChangePasswordView.as_view(), name="password-change"),

    # Parent
    path("parent/dashboard/", views.ParentDashboardView.as_view(), name="parent-dashboard"),
    path("parent/children/", views.ChildrenView.as_view(), name="parent-children"),
    path(
        "parent/children/<uuid:student_id>/results/",
        views.ChildResultsView.as_view(),
        name="parent-child-results",
    ),
    path(
        "parent/children/<uuid:student_id>/reports/",
        views.ChildReportCardsView.as_view(),
        name="parent-child-reports",
    ),
    path(
        "parent/children/<uuid:student_id>/reports/<uuid:report_id>/pdf/",
        views.ChildReportCardPDFView.as_view(),
        name="parent-child-report-pdf",
    ),
    path(
        "parent/children/<uuid:student_id>/attendance/",
        views.ChildAttendanceView.as_view(),
        name="parent-child-attendance",
    ),
    path(
        "parent/children/<uuid:student_id>/fees/",
        views.ChildFeesView.as_view(),
        name="parent-child-fees",
    ),
    path(
        "parent/announcements/",
        views.AnnouncementsView.as_view(),
        name="parent-announcements",
    ),
    path("parent/invoices/", views.ParentInvoicesView.as_view(), name="parent-invoices"),
    path(
        "parent/invoices/<uuid:invoice_id>/pdf/",
        views.ParentInvoicePDFView.as_view(),
        name="parent-invoice-pdf",
    ),
    path("parent/receipts/", views.ParentReceiptsView.as_view(), name="parent-receipts"),
    path(
        "parent/receipts/<str:reference_number>/pdf/",
        views.ParentReceiptPDFView.as_view(),
        name="parent-receipt-pdf",
    ),

    # Teacher
    path("teacher/dashboard/", views.TeacherDashboardView.as_view(), name="teacher-dashboard"),
    path("teacher/classes/", views.TeacherClassesView.as_view(), name="teacher-classes"),
    path(
        "teacher/classes/<uuid:batch_id>/register/",
        views.AttendanceRegisterView.as_view(),
        name="teacher-register",
    ),
    path("teacher/exams/", views.TeacherExamsView.as_view(), name="teacher-exams"),
    path(
        "teacher/exams/<uuid:exam_id>/marksheet/",
        views.TeacherMarkSheetView.as_view(),
        name="teacher-marksheet",
    ),
    path(
        "teacher/skills/",
        views.TeacherSkillsCatalogView.as_view(),
        name="teacher-skills-catalog",
    ),
    path(
        "teacher/skills/students/<uuid:student_id>/",
        views.TeacherStudentSkillsView.as_view(),
        name="teacher-student-skills",
    ),
    path(
        "teacher/classes/<uuid:batch_id>/skills-comments/",
        views.SkillsTeacherCommentsView.as_view(),
        name="teacher-skills-comments",
    ),
    path(
        "teacher/classes/<uuid:batch_id>/skills-submission/",
        views.SkillsSubmissionView.as_view(),
        name="teacher-skills-submission",
    ),
    path(
        "teacher/classes/<uuid:batch_id>/activities/",
        views.TeacherActivitiesView.as_view(),
        name="teacher-activities",
    ),
    path(
        "teacher/profile/signature/",
        views.TeacherSignatureView.as_view(),
        name="teacher-signature",
    ),

    # Librarian
    path("librarian/dashboard/", views.LibrarianDashboardView.as_view(), name="librarian-dashboard"),
    path("librarian/libraries/", views.LibrarianLibrariesView.as_view(), name="librarian-libraries"),
    path("librarian/books/", views.LibrarianBooksView.as_view(), name="librarian-books"),
    path("librarian/books/<uuid:book_id>/", views.LibrarianBookDetailView.as_view(), name="librarian-book-detail"),
    path("librarian/books/<uuid:book_id>/history/", views.LibrarianBookHistoryView.as_view(), name="librarian-book-history"),
    path("librarian/categories/", views.LibrarianCategoriesView.as_view(), name="librarian-categories"),
    path("librarian/batches/", views.LibrarianBatchesView.as_view(), name="librarian-batches"),
    path("librarian/batches/<uuid:batch_id>/students/", views.LibrarianBatchStudentsView.as_view(), name="librarian-batch-students"),
    path("librarian/scan/lookup/", views.LibrarianScanLookupView.as_view(), name="librarian-scan-lookup"),
    path("librarian/scan/issue/", views.LibrarianScanIssueView.as_view(), name="librarian-scan-issue"),
    path("librarian/scan/return/", views.LibrarianScanReturnView.as_view(), name="librarian-scan-return"),
    path("librarian/issued/", views.LibrarianIssuedBooksView.as_view(), name="librarian-issued"),
    path("librarian/overdue/", views.LibrarianOverdueBooksView.as_view(), name="librarian-overdue"),

    # HR portal (role: hr)
    path("hr/dashboard/", hr_views.HRDashboardView.as_view(), name="hr-dashboard"),
    path("hr/employees/", hr_views.EmployeeDirectoryView.as_view(), name="hr-employees"),
    path("hr/employees/<uuid:employee_id>/", hr_views.EmployeeDetailView.as_view(), name="hr-employee-detail"),
    path("hr/employees/<uuid:employee_id>/qualifications/", hr_views.EmployeeQualificationsView.as_view(), name="hr-employee-qualifications"),
    path("hr/employees/<uuid:employee_id>/history/", hr_views.EmployeeHistoryView.as_view(), name="hr-employee-history"),
    path("hr/employees/<uuid:employee_id>/contract/", hr_views.EmployeeContractsView.as_view(), name="hr-employee-contracts"),
    path("hr/employees/<uuid:employee_id>/documents/", hr_views.EmployeeDocumentsView.as_view(), name="hr-employee-documents"),
    path("hr/employees/<uuid:employee_id>/attendance/", hr_views.EmployeeAttendanceView.as_view(), name="hr-employee-attendance"),
    path("hr/employees/<uuid:employee_id>/onboarding/", hr_onboarding.EmployeeOnboardingView.as_view(), name="hr-employee-onboarding"),
    path("hr/onboarding/", hr_onboarding.OnboardingListView.as_view(), name="hr-onboarding"),
    path("hr/onboarding/items/<uuid:item_id>/", hr_onboarding.OnboardingItemView.as_view(), name="hr-onboarding-item"),
    path("hr/employees/<uuid:employee_id>/performance/", hr_performance.EmployeeReviewsView.as_view(), name="hr-employee-performance"),
    path("hr/performance/reviews/", hr_performance.ReviewListView.as_view(), name="hr-reviews"),
    path("hr/performance/reviews/<uuid:review_id>/", hr_performance.ReviewDetailView.as_view(), name="hr-review-detail"),
    path("hr/performance/reviews/<uuid:review_id>/complete/", hr_performance.ReviewCompleteView.as_view(), name="hr-review-complete"),
    path("hr/employees/<uuid:employee_id>/training/", hr_training.EmployeeTrainingView.as_view(), name="hr-employee-training"),
    path("hr/training/", hr_training.TrainingListView.as_view(), name="hr-training"),
    path("hr/training/compliance/", hr_training.TrainingComplianceView.as_view(), name="hr-training-compliance"),
    path("hr/training/<uuid:record_id>/", hr_training.TrainingDetailView.as_view(), name="hr-training-detail"),
    path("hr/employees/<uuid:employee_id>/exit/", hr_exit.EmployeeExitView.as_view(), name="hr-employee-exit"),
    path("hr/exit/", hr_exit.ExitListView.as_view(), name="hr-exit"),
    path("hr/exit/<uuid:exit_id>/", hr_exit.ExitDetailView.as_view(), name="hr-exit-detail"),
    path("hr/exit/<uuid:exit_id>/complete/", hr_exit.ExitCompleteView.as_view(), name="hr-exit-complete"),
    path("hr/exit/items/<uuid:item_id>/", hr_exit.ExitItemView.as_view(), name="hr-exit-item"),
    path("hr/documents/<uuid:document_id>/", hr_views.EmployeeDocumentDetailView.as_view(), name="hr-document-detail"),
    path("hr/contracts/", hr_views.ContractOrgTableView.as_view(), name="hr-contracts"),
    path("hr/contracts/<uuid:contract_id>/renew/", hr_views.ContractRenewView.as_view(), name="hr-contract-renew"),
    path("hr/contracts/<uuid:contract_id>/decision/", hr_views.ContractDecisionView.as_view(), name="hr-contract-decision"),
    path("hr/leave/", hr_views.HRLeaveListView.as_view(), name="hr-leave"),
    path("hr/leave/calendar/", hr_views.LeaveCalendarView.as_view(), name="hr-leave-calendar"),
    path("hr/leave/balances/", hr_views.LeaveBalanceView.as_view(), name="hr-leave-balances"),
    path("hr/leave/<uuid:leave_id>/supervisor-review/", hr_views.LeaveSupervisorReviewView.as_view(), name="hr-leave-supervisor-review"),
    path("hr/leave/<uuid:leave_id>/hr-review/", hr_views.LeaveHRReviewView.as_view(), name="hr-leave-hr-review"),
    path("hr/attendance/", hr_views.AttendanceListView.as_view(), name="hr-attendance"),
    path("hr/attendance/analytics/", hr_views.AttendanceAnalyticsView.as_view(), name="hr-attendance-analytics"),
    path("hr/tasks/", hr_views.HRTaskListView.as_view(), name="hr-tasks"),
    path("hr/tasks/<uuid:task_id>/", hr_views.HRTaskDetailView.as_view(), name="hr-task-detail"),
    path("hr/audit/", hr_views.AuditLogView.as_view(), name="hr-audit"),
    path("hr/analytics/", hr_views.HRAnalyticsView.as_view(), name="hr-analytics"),
    path("hr/policies/", hr_policies.PolicyListView.as_view(), name="hr-policies"),
    path("hr/policies/<uuid:policy_id>/", hr_policies.PolicyDetailView.as_view(), name="hr-policy-detail"),
    path("hr/policies/<uuid:policy_id>/acknowledgements/", hr_policies.PolicyAcknowledgementsView.as_view(), name="hr-policy-acks"),
    path("hr/disciplinary/", hr_relations.DisciplinaryListView.as_view(), name="hr-disciplinary"),
    path("hr/disciplinary/<uuid:case_id>/", hr_relations.DisciplinaryDetailView.as_view(), name="hr-disciplinary-detail"),
    path("hr/employees/<uuid:employee_id>/disciplinary/", hr_relations.EmployeeDisciplinaryView.as_view(), name="hr-employee-disciplinary"),
    path("hr/grievances/", hr_relations.GrievanceListView.as_view(), name="hr-grievances"),
    path("hr/grievances/<uuid:grievance_id>/", hr_relations.GrievanceDetailView.as_view(), name="hr-grievance-detail"),
    path("hr/recruitment/vacancies/", hr_recruitment.VacancyListView.as_view(), name="hr-vacancies"),
    path("hr/recruitment/vacancies/<uuid:vacancy_id>/", hr_recruitment.VacancyDetailView.as_view(), name="hr-vacancy-detail"),
    path("hr/recruitment/vacancies/<uuid:vacancy_id>/applicants/", hr_recruitment.VacancyApplicantsView.as_view(), name="hr-vacancy-applicants"),
    path("hr/recruitment/applicants/<uuid:applicant_id>/", hr_recruitment.ApplicantDetailView.as_view(), name="hr-applicant-detail"),
    path("hr/recruitment/applicants/<uuid:applicant_id>/advance/", hr_recruitment.ApplicantAdvanceView.as_view(), name="hr-applicant-advance"),
    path("hr/recruitment/applicants/<uuid:applicant_id>/convert/", hr_recruitment.ApplicantConvertView.as_view(), name="hr-applicant-convert"),
    path("hr/settings/lookups/<str:lookup_key>/", hr_settings_views.HRLookupListView.as_view(), name="hr-settings-lookups"),
    path("hr/settings/lookups/<str:lookup_key>/<uuid:pk>/", hr_settings_views.HRLookupDetailView.as_view(), name="hr-settings-lookup-detail"),
    path("hr/settings/working-days/", hr_settings_views.HRWorkingDaySettingsView.as_view(), name="hr-settings-working-days"),
    path("hr/settings/document-types/", hr_settings_views.HRDocumentTypesView.as_view(), name="hr-settings-document-types"),

    # Payroll
    path("hr/payroll/payslips/", payroll_views.PayslipListView.as_view(), name="hr-payslips"),
    path("hr/payroll/payslips/generate/", payroll_views.PayslipGenerateView.as_view(), name="hr-payslip-generate"),
    path("hr/payroll/payslips/<uuid:payslip_id>/", payroll_views.PayslipDetailView.as_view(), name="hr-payslip-detail"),
    path("hr/payroll/payslips/<uuid:payslip_id>/<str:action>/", payroll_views.PayslipActionView.as_view(), name="hr-payslip-action"),
    path("hr/payroll/categories/", payroll_views.PayrollCategoryView.as_view(), name="hr-payroll-categories"),
    path("hr/payroll/categories/<uuid:pk>/", payroll_views.PayrollCategoryDetailView.as_view(), name="hr-payroll-category-detail"),
    path("hr/payroll/groups/", payroll_views.PayrollGroupView.as_view(), name="hr-payroll-groups"),
    path("hr/payroll/groups/<uuid:pk>/", payroll_views.PayrollGroupDetailView.as_view(), name="hr-payroll-group-detail"),
    path("hr/payroll/groups/<uuid:pk>/components/", payroll_views.PayrollGroupComponentView.as_view(), name="hr-payroll-group-components"),
    path("hr/payroll/groups/<uuid:pk>/components/<uuid:component_id>/", payroll_views.PayrollGroupComponentView.as_view(), name="hr-payroll-group-component-detail"),
    path("hr/payroll/settings/", payroll_views.PayslipSettingsView.as_view(), name="hr-payroll-settings"),
    path("hr/employees/<uuid:employee_id>/payroll/", payroll_views.EmployeePayrollView.as_view(), name="hr-employee-payroll"),
    path("hr/reports/", hr_reports.HRReportIndexView.as_view(), name="hr-reports"),
    path("hr/reports/<slug:slug>/", hr_reports.HRReportView.as_view(), name="hr-report"),
    path("hr/me/profile/", hr_views.MyHRProfileView.as_view(), name="hr-me-profile"),
    path("hr/me/attendance/", hr_views.MyAttendanceView.as_view(), name="hr-me-attendance"),
    path("hr/me/leave/", hr_views.MyLeaveView.as_view(), name="hr-me-leave"),
    path("hr/me/leave/balance/", hr_views.MyLeaveBalanceView.as_view(), name="hr-me-leave-balance"),
    path("hr/me/payslips/", payroll_views.MyPayslipsView.as_view(), name="hr-me-payslips"),
    path("hr/me/payslips/<uuid:payslip_id>/", payroll_views.MyPayslipDetailView.as_view(), name="hr-me-payslip-detail"),
    path("hr/me/contracts/", hr_views.MyContractsView.as_view(), name="hr-me-contracts"),
    path("hr/me/documents/", hr_views.MyDocumentsView.as_view(), name="hr-me-documents"),
    path("hr/me/policies/", hr_policies.MyPoliciesView.as_view(), name="hr-me-policies"),
    path("hr/me/policies/<uuid:policy_id>/acknowledge/", hr_policies.MyPolicyAcknowledgeView.as_view(), name="hr-me-policy-acknowledge"),
    path("hr/me/reviews/", hr_performance.MyReviewsView.as_view(), name="hr-me-reviews"),
    path("hr/me/reviews/<uuid:review_id>/", hr_performance.MyReviewDetailView.as_view(), name="hr-me-review-detail"),

    # Public admission (no auth required)
    path("admission/courses/", views.AdmissionCoursesView.as_view(), name="admission-courses"),
    path("admission/apply/", views.AdmissionApplyView.as_view(), name="admission-apply"),
    path("admission/status/", views.AdmissionStatusView.as_view(), name="admission-status"),

    # Public enquiry (no auth required)
    path("enquiry/submit/", views.EnquirySubmitView.as_view(), name="enquiry-submit"),
]
