name: PYTEST 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: django-insecure-04p@%t4gven4uvy!eb)o2)e=e*k@7no3@7hae=a=ms0l3t)-2j
      DATABASE_ENGINE: django_tenants.postgresql_backend
      DATABASE_HOST: localhost
      DATABASE_PORT: "5432"
      DATABASE_NAME: test_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres

    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.12"]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Check for missing migrations
        run: poetry run python manage.py makemigrations --check --dry-run

      - name: Django system checks
        run: poetry run python manage.py check

      - name: Run migrations
        run: poetry run python manage.py migrate --noinput

      - name: CPU Info
        run: |
          nproc
          lscpu

      - name: Run tests
        run: poetry run pytest -n auto --durations=20